// ─── Translation strings for all 6 languages ──────────────────────────────────
// Keys are used via: const { t } = useTranslation(); t('key')

const translations = {
  en: {
    // App / Sidebar
    appName: 'AgriN',
    appSubtitle: 'BRICS Digital Network',
    overview: 'Overview',
    aiTools: 'AI Tools',
    farmIntelligence: 'Farm Intelligence',
    marketsAndCommunity: 'Markets & Community',
    settings: 'Settings',
    logout: 'Logout',
    loggedInAs: 'Logged in as',

    // Nav items
    dashboard: 'Dashboard',
    smartAlerts: 'Smart Alerts',
    cropDiagnostics: 'Crop Diagnostics',
    agroBot: 'AgroBot AI',
    satelliteMap: 'Satellite Map',
    weather: 'Weather',
    yieldPredictor: 'Yield Predictor',
    fieldScouting: 'Field Scouting',
    marketPrices: 'Market Prices',
    bricsExchange: 'BRICS Exchange',

    // Dashboard
    goodMorning: 'Good morning',
    goodAfternoon: 'Good afternoon',
    goodEvening: 'Good evening',
    farmer: 'Farmer',
    soilHealth: 'Soil Health',
    optimal: 'OPTIMAL',
    moisture: 'Moisture',
    phLevel: 'pH Level',
    nitrogen: 'Nitrogen (N)',
    phosphorus: 'Phosphorus (P)',
    currentConditions: 'Current Conditions',
    temperature: 'Temperature',
    humidity: 'Humidity',
    windSpeed: 'Wind Speed',
    uvIndex: 'UV Index',
    farmOverview: 'Farm Overview',
    activeFields: 'Active Fields',
    cropHealthAvg: 'Crop Health Avg',
    pendingAlerts: 'Pending Alerts',
    nextHarvest: 'Next Harvest',
    cropVigorNDVI: 'Crop Vigor (NDVI) — 6-Week Trend',
    sentinelData: 'Sentinel-2 Satellite Data',
    aiAdvisories: 'AI Agro-Advisories',
    coverCropping: 'Cover Cropping Suggested',
    irrigationAlert: 'Irrigation Alert',

    // Login
    welcomeBack: 'Welcome Back',
    signInAccount: 'Sign in to your account',
    createAccount: 'Create Account',
    joinNetwork: 'Join the BRICS Agricultural Network',
    email: 'Email',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    fullName: 'Full Name',
    country: 'Country',
    signIn: 'Sign In',
    register: 'Register',
    noAccount: "Don't have an account?",
    hasAccount: 'Already have an account?',
    signingIn: 'Signing in...',
    registering: 'Registering...',
    passwordStrength: 'Password Strength',
    weak: 'Weak',
    fair: 'Fair',
    strong: 'Strong',
    veryStrong: 'Very Strong',

    // Weather
    sevenDayForecast: '7-Day Outlook',
    precipitationProb: 'Precipitation Probability (7 days)',
    aiFarmSchedule: 'AI Farm Schedule',
    rainChance: 'Rain Chance',
    wind: 'Wind',
    refresh: 'Refresh',

    // Knowledge Exchange
    knowledgeExchange: 'Knowledge Exchange',
    shareKnowledge: 'Share Knowledge',
    publishToBrics: 'Publish to BRICS Network',
    searchTechniques: 'Search techniques...',
    yourFarmingTechnique: 'Share Your Farming Technique',
    title: 'Title',
    content: 'Content',
    tags: 'Tags',
    cancel: 'Cancel',
    replies: 'replies',
    autoTranslated: 'Auto-translated',

    // Market Prices
    marketPricesTitle: 'Market Prices',
    refreshPrices: 'Refresh Prices',
    lastUpdated: 'Last updated',
    sellNow: 'SELL NOW',
    hold: 'HOLD',
    buyDip: 'BUY DIP',
    aiSignal: 'AI Signal',

    // Yield Predictor
    yieldPredictorTitle: 'Yield Predictor',
    tonsPerHa: 'tons / hectare',
    confidence: 'Confidence',
    estHarvest: 'Est. Harvest',
    growthProgress: 'Growth Progress',
    adjustFactors: 'Adjust Factors (drag to simulate)',
    yieldFactors: 'Yield Factors',
    cropGrowthCalendar: 'Crop Growth Calendar',
    historicalYield: 'Historical Yield Performance (tons/ha)',

    // Field Scouting
    fieldScouting: 'Field Scouting',
    newScoutReport: 'New Scout Report',
    totalReports: 'Total Reports',
    highSeverity: 'High Severity',
    fieldsScouted: 'Fields Scouted',
    field: 'Field',
    crop: 'Crop',
    latitude: 'Latitude',
    longitude: 'Longitude',
    useGPS: 'Use GPS',
    severity: 'Severity',
    observations: 'Observations & Notes',
    uploadPhoto: 'Click to upload field photo',
    saveReport: 'Save Report',
    scoutHistory: 'Scout History',
    low: 'Low',
    medium: 'Medium',
    high: 'High',

    // Alerts
    smartAlertsTitle: 'Smart Alerts',
    markAllRead: 'Mark all read',
    disease: 'Disease',
    weatherAlert: 'Weather',
    market: 'Market',
    irrigation: 'Irrigation',
    resolveAlert: 'Resolve Alert',
    dismiss: 'Dismiss',
    recommendedAction: 'Recommended Action',

    // AgroBot
    agrobotTitle: 'AgroBot AI Assistant',
    agrobotSubtitle: 'Trained on BRICS agricultural datasets · Live backend responses',
    newChat: 'New Chat',
    askAgrobot: 'Ask AgroBot anything about your farm...',
    agrobotDisclaimer: 'AgroBot provides AI-assisted guidance. Always consult a local agronomist for critical decisions.',

    // Satellite Map
    satelliteMapTitle: 'Satellite Field Map',
    satelliteSubtitle: 'Real-time NDVI overlay · Sentinel-2 · Last updated 2 hours ago',
    avgFarmNdvi: 'Avg Farm NDVI',
    totalFarmArea: 'Total Farm Area',
    activeStressZones: 'Active Stress Zones',

    // Common
    offline: 'Offline',
    retry: 'Retry',
    loading: 'Loading...',
    noData: 'No data available',
    aboveAvg: 'Above regional avg',
    whatShouldIDoToday: 'What should I do today?',
    whatShouldIDoTodayDesc: 'Based on recent weather and your crop cycle, here is the most important action.',
    sprayFungicideNow: 'Spray Fungicide Now',
    highHumidityExpected: 'High humidity (+80%) expected tomorrow. Prevent leaf blight.',
    viewDetails: 'View Details',
    verified: 'Verified',
    usedSuccessfullyByFarmers: 'Used successfully by 47 farmers in your block this season.',
    sprayFungicideNowDesc: 'Based on recent weather and your crop cycle, here is the most important action. Spray fungicide today before the rains start tomorrow.',
    financialServices: 'Financial Services',
    laborAndEquipment: 'Labor & Equipment',
    seedsAndInputs: 'Seeds & Inputs',
    postHarvest: 'Post-Harvest',
    transitionSupport: 'Transition Support',
    womenFarmers: 'Women Farmers',
    govtSchemes: 'Govt Schemes',
    communityAndTrust: 'Community & Trust',
    offlineMode: 'Offline Mode',
    syncQueueManager: 'Sync Queue Manager',
    smsAndUssdLite: 'SMS & USSD Lite',
    dataPrivacyAndBrics: 'Data Privacy & BRICS',
    batterySaver: 'Battery Saver',
    progressiveBundles: 'Progressive Bundles',
    farmerServices: 'Farmer Services',
    supportAndCommunity: 'Support & Community',
    marketRatesCropNews: 'Market Rates & Crop News',
    realTimeMandiRates: 'Real-Time Mandi Rates',
    realTimeCropNews: 'Real-Time Crop & Mandi News',
    liveLocationNewsAdvisories: 'Live location-based agricultural news and official advisories for',
    localPeerProof: 'Local Peer Proof',
    similarFarms: 'Similar farms',
    creditLoanMatching: 'Credit & Loan Matching',
    personalizedFinancing: 'Personalized financing options matched to your farm profile and location.',
    maxAmount: 'Max Amount',
    interestRate: 'Interest Rate',
    processing: 'Processing',
    days: 'days',
    listen: 'Listen', stop: 'Stop', tapToListen: 'Tap to listen',
  },
  mr: {
    appName: 'AgriN', appSubtitle: 'BRICS डिजिटल नेटवर्क',
    overview: 'आढावा', aiTools: 'AI साधने', farmIntelligence: 'शेती बुद्धिमत्ता', marketsAndCommunity: 'बाजार आणि समुदाय',
    settings: 'सेटिंग्ज', logout: 'लॉगआउट', loggedInAs: 'लॉग इन:', dashboard: 'डॅशबोर्ड',
    smartAlerts: 'स्मार्ट सूचना', cropDiagnostics: 'पीक निदान', agroBot: 'अ‍ॅग्रोबोट AI', satelliteMap: 'सॅटेलाइट नकाशा',
    weather: 'हवामान', yieldPredictor: 'उत्पन्न अंदाज', fieldScouting: 'फिल्ड स्काउटिंग', marketPrices: 'बाजार भाव',
    bricsExchange: 'ज्ञान विनिमय', goodMorning: 'शुभ सकाळ', goodAfternoon: 'शुभ दुपार', goodEvening: 'शुभ संध्याकाळ',
    farmer: 'शेतकरी', soilHealth: 'मातीचे आरोग्य', optimal: 'इष्टतम', moisture: 'ओलावा', phLevel: 'pH पातळी',
    nitrogen: 'नायट्रोजन (N)', phosphorus: 'फॉस्फरस (P)', currentConditions: 'सध्याची स्थिती', temperature: 'तापमान',
    humidity: 'आर्द्रता', windSpeed: 'वाऱ्याचा वेग', uvIndex: 'अतिनील निर्देशांक', farmOverview: 'शेत आढावा',
    activeFields: 'सक्रिय शेती', cropHealthAvg: 'पिकाचे आरोग्य सरासरी', pendingAlerts: 'प्रलंबित सूचना', nextHarvest: 'पुढील कापणी',
    cropVigorNDVI: 'पिकाची वाढ (NDVI)', sentinelData: 'Sentinel-2 डेटा', aiAdvisories: 'AI सल्ला', coverCropping: 'कव्हर क्रॉपिंग शिफारस',
    irrigationAlert: 'सिंचन सूचना', welcomeBack: 'पुन्हा स्वागत आहे', signInAccount: 'खात्यात साइन इन करा', createAccount: 'खाते तयार करा',
    joinNetwork: 'BRICS कृषी नेटवर्कमध्ये सामील व्हा', email: 'ईमेल', password: 'पासवर्ड', confirmPassword: 'पासवर्डची पुष्टी करा',
    fullName: 'पूर्ण नाव', country: 'देश', signIn: 'साइन इन', register: 'नोंदणी करा', noAccount: 'खाते नाही?', hasAccount: 'खाते आहे?',
    signingIn: 'साइन इन करत आहे...', registering: 'नोंदणी करत आहे...', passwordStrength: 'पासवर्डची ताकद', weak: 'कमकुवत', fair: 'मध्यम', strong: 'म मजबूत', veryStrong: 'खूप मजबूत',
    sevenDayForecast: '७-दिवसांचा अंदाज', precipitationProb: 'पावसाची शक्यता', aiFarmSchedule: 'AI शेती वेळापत्रक', rainChance: 'पावसाची शक्यता', wind: 'वारा', refresh: 'रिफ्रेश',
    knowledgeExchange: 'ज्ञान विनिमय', shareKnowledge: 'ज्ञान शेअर करा', publishToBrics: 'प्रकाशित करा', searchTechniques: 'तंत्र शोधा...',
    cancel: 'रद्द करा', replies: 'उत्तरे', autoTranslated: 'स्वयं-अनुवादित', marketPricesTitle: 'बाजार भाव', refreshPrices: 'किमती रिफ्रेश करा', lastUpdated: 'अंतिम अपडेट',
    sellNow: 'आता विका', hold: 'होल्ड करा', buyDip: 'खरेदी करा', aiSignal: 'AI संकेत', yieldPredictorTitle: 'उत्पन्न अंदाज', tonsPerHa: 'टन/हेक्टर',
    confidence: 'आत्मविश्वास', estHarvest: 'अंदाजित कापणी', growthProgress: 'वाढ प्रगती', adjustFactors: 'घटक समायोजित करा', yieldFactors: 'उत्पन्न घटक',
    cropGrowthCalendar: 'पीक वाढ कॅलेंडर', historicalYield: 'ऐतिहासिक उत्पन्न (टन/हे)', fieldScouting: 'फिल्ड स्काउटिंग', newScoutReport: 'नवीन अहवाल',
    totalReports: 'एकूण अहवाल', highSeverity: 'उच्च तीव्रता', fieldsScouted: 'स्काउट केलेली शेती', field: 'शेती', crop: 'पीक', latitude: 'अक्षांश', longitude: 'रेखांश',
    useGPS: 'जीपीएस वापरा', severity: 'तीव्रता', observations: 'निरीक्षणे', uploadPhoto: 'फोटो अपलोड करा', saveReport: 'अहवाल जतन करा',
    scoutHistory: 'स्काउट इतिहास', low: 'कमी', medium: 'मध्यम', high: 'जास्त', smartAlertsTitle: 'स्मार्ट सूचना', markAllRead: 'सर्व वाचलेले म्हणून चिन्हांकित करा',
    disease: 'रोग', weatherAlert: 'हवामान', market: 'बाजार', irrigation: 'सिंचन', resolveAlert: 'सूचना सोडवा', dismiss: 'काढून टाका', recommendedAction: 'शिफारस केलेली कृती',
    agrobotTitle: 'अ‍ॅग्रोबोट AI सहाय्यक', agrobotSubtitle: 'BRICS डेटासेटवर प्रशिक्षित', newChat: 'नवीन गप्पा', askAgrobot: 'तुमच्या शेतीबद्दल अ‍ॅग्रोबोटला विचारा...',
    agrobotDisclaimer: 'अ‍ॅग्रोबोट AI मार्गदर्शन देते. महत्त्वाच्या निर्णयांसाठी स्थानिक तज्ज्ञांचा सल्ला घ्या.', satelliteMapTitle: 'सॅटेलाइट नकाशा', satelliteSubtitle: 'रिअल-टाइम NDVI · Sentinel-2',
    avgFarmNdvi: 'सरासरी NDVI', totalFarmArea: 'एकूण शेती क्षेत्र', activeStressZones: 'सक्रिय ताण क्षेत्र', offline: 'ऑफलाइन', retry: 'पुन्हा प्रयत्न करा',
    loading: 'लोड होत आहे...', noData: 'कोणताही डेटा नाही', aboveAvg: 'प्रादेशिक सरासरीच्या वर', yourFarmingTechnique: 'तुमचे शेती तंत्र शेअर करा', title: 'शीर्षक', content: 'सामग्री', tags: 'टॅग',
    whatShouldIDoToday: 'मी आज काय करावे?', whatShouldIDoTodayDesc: 'हवामान आणि पीक चक्रावर आधारित, ही सर्वात महत्त्वाची कृती आहे.', sprayFungicideNow: 'आता बुरशीनाशक फवारणी करा',
    highHumidityExpected: 'उद्या जास्त आर्द्रता अपेक्षित आहे. करपा टाळा.', viewDetails: 'तपशील पहा', verified: 'सत्यापित', usedSuccessfullyByFarmers: 'तुमच्या भागातील 47 शेतकऱ्यांनी यशस्वीपणे वापरले.',
    sprayFungicideNowDesc: 'हवामान आणि पीक चक्रावर आधारित ही सर्वात महत्त्वाची कृती आहे.', financialServices: 'वित्तीय सेवा', laborAndEquipment: 'कामगार आणि उपकरणे', seedsAndInputs: 'बियाणे आणि निविष्ठा',
    postHarvest: 'कापणीनंतरचे व्यवस्थापन', transitionSupport: 'संक्रमण समर्थन', womenFarmers: 'महिला शेतकरी', govtSchemes: 'सरकारी योजना', communityAndTrust: 'समुदाय आणि विश्वास',
    offlineMode: 'ऑफलाइन मोड', syncQueueManager: 'सिंक क्यू मॅनेजर', smsAndUssdLite: 'SMS आणि USSD लाईट', dataPrivacyAndBrics: 'डेटा प्रायव्हसी आणि ब्रिक्स', batterySaver: 'बॅटरी सेव्हर',
    progressiveBundles: 'प्रगत बंडल', farmerServices: 'शेतकरी सेवा', supportAndCommunity: 'समर्थन आणि समुदाय', marketRatesCropNews: 'बाजार भाव आणि पीक बातम्या',
    realTimeMandiRates: 'रिअल-टाइम बाजार भाव', realTimeCropNews: 'रिअल-टाइम पीक बातम्या', liveLocationNewsAdvisories: 'तुमच्यासाठी स्थानिक शेती बातम्या',
    localPeerProof: 'स्थानिक सहकाऱ्यांचा पुरावा', similarFarms: 'समान शेती', creditLoanMatching: 'क्रेडिट आणि कर्ज', personalizedFinancing: 'वैयक्तिकृत कर्ज पर्याय.',
    maxAmount: 'कमाल रक्कम', interestRate: 'व्याजदर', processing: 'प्रक्रिया', days: 'दिवस',
    uiToday: 'आज', humShort: 'आर्द्रता', rain: 'पाऊस', priority: 'प्राधान्य', uiQuickTools: 'जलद साधने',
    marketRates: 'बाजार भाव', govtSchemesShort: 'योजना', financingOptions: 'कर्ज पर्याय',
    listen: 'ऐका', stop: 'थांबा', tapToListen: 'ऐकण्यासाठी दाबा',
  },
  hi: {
    appName: 'AgriN',
    appSubtitle: 'BRICS डिजिटल नेटवर्क',
    overview: 'अवलोकन',
    aiTools: 'AI उपकरण',
    farmIntelligence: 'कृषि बुद्धिमत्ता',
    marketsAndCommunity: 'बाज़ार और समुदाय',
    settings: 'सेटिंग्स',
    logout: 'लॉग आउट',
    loggedInAs: 'लॉग इन है',
    dashboard: 'डैशबोर्ड',
    smartAlerts: 'स्मार्ट अलर्ट',
    cropDiagnostics: 'फसल निदान',
    agroBot: 'AgroBot AI',
    satelliteMap: 'सैटेलाइट मानचित्र',
    weather: 'मौसम',
    yieldPredictor: 'उपज भविष्यवक्ता',
    fieldScouting: 'क्षेत्र सर्वेक्षण',
    marketPrices: 'बाज़ार भाव',
    bricsExchange: 'BRICS ज्ञान केंद्र',
    goodMorning: 'सुप्रभात',
    goodAfternoon: 'नमस्ते',
    goodEvening: 'शुभ संध्या',
    farmer: 'किसान',
    soilHealth: 'मिट्टी स्वास्थ्य',
    optimal: 'इष्टतम',
    moisture: 'नमी',
    phLevel: 'pH स्तर',
    nitrogen: 'नाइट्रोजन (N)',
    phosphorus: 'फास्फोरस (P)',
    currentConditions: 'वर्तमान स्थिति',
    temperature: 'तापमान',
    humidity: 'आर्द्रता',
    windSpeed: 'हवा की गति',
    uvIndex: 'UV सूचकांक',
    farmOverview: 'खेत अवलोकन',
    activeFields: 'सक्रिय खेत',
    cropHealthAvg: 'फसल स्वास्थ्य औसत',
    pendingAlerts: 'लंबित अलर्ट',
    nextHarvest: 'अगली कटाई',
    cropVigorNDVI: 'फसल जोश (NDVI) — 6 सप्ताह',
    sentinelData: 'Sentinel-2 उपग्रह डेटा',
    aiAdvisories: 'AI कृषि सलाह',
    coverCropping: 'कवर क्रॉपिंग सुझाव',
    irrigationAlert: 'सिंचाई अलर्ट',
    whatShouldIDoToday: 'आज मुझे क्या करना चाहिए?',
    whatShouldIDoTodayDesc: 'हाल के मौसम और आपके फसल चक्र के आधार पर, यह सबसे महत्वपूर्ण कार्रवाई है।',
    sprayFungicideNow: 'अब फफूंदनाशक का छिड़काव करें',
    highHumidityExpected: 'कल उच्च आर्द्रता (+80%) होने की उम्मीद है। पत्तियों के झुलसने से बचाव करें।',
    viewDetails: 'विवरण देखें',
    verified: 'सत्यापित',
    usedSuccessfullyByFarmers: 'इस सीज़न में आपके ब्लॉक में 47 किसानों द्वारा सफलतापूर्वक उपयोग किया गया।',
    sprayFungicideNowDesc: 'हाल के मौसम और आपके फसल चक्र के आधार पर, यह सबसे महत्वपूर्ण कार्रवाई है। कल बारिश शुरू होने से पहले आज फफूंदनाशक का छिड़काव करें।',
    welcomeBack: 'वापस स्वागत है',
    signInAccount: 'अपने खाते में साइन इन करें',
    createAccount: 'खाता बनाएं',
    joinNetwork: 'BRICS कृषि नेटवर्क से जुड़ें',
    email: 'ईमेल',
    password: 'पासवर्ड',
    confirmPassword: 'पासवर्ड की पुष्टि करें',
    fullName: 'पूरा नाम',
    country: 'देश',
    signIn: 'साइन इन',
    register: 'पंजीकरण',
    noAccount: 'खाता नहीं है?',
    hasAccount: 'पहले से खाता है?',
    signingIn: 'साइन इन हो रहा है...',
    registering: 'पंजीकरण हो रहा है...',
    passwordStrength: 'पासवर्ड शक्ति',
    weak: 'कमज़ोर', fair: 'ठीक', strong: 'मज़बूत', veryStrong: 'बहुत मज़बूत',
    sevenDayForecast: '7-दिन पूर्वानुमान',
    precipitationProb: 'वर्षा संभावना (7 दिन)',
    aiFarmSchedule: 'AI कृषि कार्यक्रम',
    rainChance: 'बारिश संभावना',
    wind: 'हवा',
    refresh: 'ताज़ा करें',
    knowledgeExchange: 'ज्ञान आदान-प्रदान',
    shareKnowledge: 'ज्ञान साझा करें',
    publishToBrics: 'BRICS नेटवर्क पर प्रकाशित करें',
    searchTechniques: 'तकनीकें खोजें...',
    cancel: 'रद्द करें',
    replies: 'उत्तर',
    autoTranslated: 'स्वतः अनुवादित',
    marketPricesTitle: 'बाज़ार भाव',
    refreshPrices: 'भाव ताज़ा करें',
    lastUpdated: 'अंतिम अपडेट',
    sellNow: 'अभी बेचें', hold: 'रोकें', buyDip: 'खरीदें', aiSignal: 'AI संकेत',
    yieldPredictorTitle: 'उपज भविष्यवक्ता',
    tonsPerHa: 'टन/हेक्टेयर',
    confidence: 'विश्वास',
    estHarvest: 'अनुमानित कटाई',
    growthProgress: 'विकास प्रगति',
    adjustFactors: 'कारक समायोजित करें',
    yieldFactors: 'उपज कारक',
    cropGrowthCalendar: 'फसल विकास कैलेंडर',
    historicalYield: 'ऐतिहासिक उपज (टन/हेक्टेयर)',
    fieldScouting: 'क्षेत्र सर्वेक्षण',
    newScoutReport: 'नई सर्वेक्षण रिपोर्ट',
    totalReports: 'कुल रिपोर्ट', highSeverity: 'उच्च गंभीरता', fieldsScouted: 'सर्वेक्षण खेत',
    field: 'खेत', crop: 'फसल', latitude: 'अक्षांश', longitude: 'देशांतर',
    useGPS: 'GPS उपयोग करें', severity: 'गंभीरता',
    observations: 'अवलोकन और टिप्पणियाँ', uploadPhoto: 'फ़ोटो अपलोड करें', saveReport: 'रिपोर्ट सहेजें',
    scoutHistory: 'सर्वेक्षण इतिहास', low: 'कम', medium: 'मध्यम', high: 'उच्च',
    smartAlertsTitle: 'स्मार्ट अलर्ट', markAllRead: 'सभी पढ़े हुए चिह्नित करें',
    disease: 'रोग', weatherAlert: 'मौसम', market: 'बाज़ार', irrigation: 'सिंचाई',
    resolveAlert: 'अलर्ट हल करें', dismiss: 'खारिज करें', recommendedAction: 'अनुशंसित कार्रवाई',
    agrobotTitle: 'AgroBot AI सहायक', agrobotSubtitle: 'BRICS कृषि डेटासेट पर प्रशिक्षित',
    newChat: 'नई चैट', askAgrobot: 'AgroBot से अपने खेत के बारे में कुछ भी पूछें...',
    agrobotDisclaimer: 'AgroBot AI सहायता प्रदान करता है। महत्वपूर्ण निर्णयों के लिए स्थानीय कृषि विशेषज्ञ से परामर्श करें।',
    satelliteMapTitle: 'सैटेलाइट मानचित्र', satelliteSubtitle: 'रियल-टाइम NDVI ओवरले · Sentinel-2',
    avgFarmNdvi: 'औसत NDVI', totalFarmArea: 'कुल खेत क्षेत्र', activeStressZones: 'सक्रिय तनाव क्षेत्र',
    offline: 'ऑफलाइन', retry: 'पुनः प्रयास', loading: 'लोड हो रहा है...', noData: 'डेटा उपलब्ध नहीं', aboveAvg: 'क्षेत्रीय औसत से ऊपर',
    yourFarmingTechnique: 'अपनी कृषि तकनीक साझा करें', title: 'शीर्षक', content: 'सामग्री', tags: 'टैग',
  },

  ta: {
    appName: 'AgriN',
    appSubtitle: 'BRICS டிஜிட்டல் நெட்வொர்க்',
    overview: 'கண்ணோட்டம்',
    aiTools: 'AI கருவிகள்',
    farmIntelligence: 'வேளாண் நுண்ணறிவு',
    marketsAndCommunity: 'சந்தை மற்றும் சமுதாயம்',
    settings: 'அமைப்புகள்',
    logout: 'வெளியேறு',
    loggedInAs: 'உள்நுழைந்துள்ளீர்கள்',
    dashboard: 'டாஷ்போர்டு',
    smartAlerts: 'ஸ்மார்ட் எச்சரிக்கைகள்',
    cropDiagnostics: 'பயிர் நோய் கண்டறிதல்',
    agroBot: 'AgroBot AI',
    satelliteMap: 'செயற்கைக்கோள் வரைபடம்',
    weather: 'வானிலை',
    yieldPredictor: 'விளைச்சல் கணிப்பான்',
    fieldScouting: 'வயல் கண்காணிப்பு',
    marketPrices: 'சந்தை விலைகள்',
    bricsExchange: 'BRICS அறிவு மையம்',
    goodMorning: 'காலை வணக்கம்',
    goodAfternoon: 'மதிய வணக்கம்',
    goodEvening: 'மாலை வணக்கம்',
    farmer: 'விவசாயி',
    soilHealth: 'மண் ஆரோக்கியம்',
    optimal: 'சிறந்தது',
    moisture: 'ஈரப்பதம்',
    phLevel: 'pH அளவு',
    nitrogen: 'நைட்ரஜன் (N)',
    phosphorus: 'பாஸ்பரஸ் (P)',
    currentConditions: 'தற்போதைய நிலைமைகள்',
    temperature: 'வெப்பநிலை',
    humidity: 'ஈரப்பதம்',
    windSpeed: 'காற்று வேகம்',
    uvIndex: 'UV குறியீடு',
    farmOverview: 'பண்ணை கண்ணோட்டம்',
    activeFields: 'செயலில் உள்ள வயல்கள்',
    cropHealthAvg: 'பயிர் ஆரோக்கிய சராசரி',
    pendingAlerts: 'நிலுவையில் உள்ள எச்சரிக்கைகள்',
    nextHarvest: 'அடுத்த அறுவடை',
    cropVigorNDVI: 'பயிர் வீரியம் (NDVI) — 6 வாரங்கள்',
    sentinelData: 'Sentinel-2 செயற்கைக்கோள் தரவு',
    aiAdvisories: 'AI வேளாண் ஆலோசனைகள்',
    coverCropping: 'மூட பயிரிடல் பரிந்துரை',
    irrigationAlert: 'நீர்ப்பாசன எச்சரிக்கை',
    welcomeBack: 'மீண்டும் வரவேற்கிறோம்',
    signInAccount: 'உங்கள் கணக்கில் உள்நுழையவும்',
    createAccount: 'கணக்கு உருவாக்கவும்',
    joinNetwork: 'BRICS வேளாண் நெட்வொர்க்கில் சேரவும்',
    email: 'மின்னஞ்சல்',
    password: 'கடவுச்சொல்',
    confirmPassword: 'கடவுச்சொல் உறுதிப்படுத்தவும்',
    fullName: 'முழு பெயர்',
    country: 'நாடு',
    signIn: 'உள்நுழை',
    register: 'பதிவு செய்க',
    noAccount: 'கணக்கு இல்லையா?',
    hasAccount: 'ஏற்கெனவே கணக்கு உள்ளதா?',
    signingIn: 'உள்நுழைகிறது...', registering: 'பதிவு செய்கிறது...',
    passwordStrength: 'கடவுச்சொல் வலிமை',
    weak: 'பலவீனம்', fair: 'நடுத்தரம்', strong: 'வலிமையானது', veryStrong: 'மிகவும் வலிமையானது',
    sevenDayForecast: '7-நாள் வானிலை',
    precipitationProb: 'மழை நிகழ்தகவு (7 நாட்கள்)',
    aiFarmSchedule: 'AI பண்ணை அட்டவணை',
    rainChance: 'மழை வாய்ப்பு', wind: 'காற்று', refresh: 'புதுப்பிக்கவும்',
    knowledgeExchange: 'அறிவு பரிமாற்றம்', shareKnowledge: 'அறிவை பகிரவும்',
    publishToBrics: 'BRICS நெட்வொர்க்கில் வெளியிடவும்', searchTechniques: 'நுட்பங்களை தேடுங்கள்...',
    cancel: 'ரத்து செய்', replies: 'பதில்கள்', autoTranslated: 'தானாக மொழிபெயர்க்கப்பட்டது',
    marketPricesTitle: 'சந்தை விலைகள்', refreshPrices: 'விலைகளை புதுப்பிக்கவும்', lastUpdated: 'கடைசியாக புதுப்பிக்கப்பட்டது',
    sellNow: 'இப்போது விற்கவும்', hold: 'தொடர்ந்து வைத்திருங்கள்', buyDip: 'வாங்கவும்', aiSignal: 'AI சமிக்ஞை',
    yieldPredictorTitle: 'விளைச்சல் கணிப்பான்', tonsPerHa: 'டன்/எக்டர்',
    confidence: 'நம்பகத்தன்மை', estHarvest: 'மதிப்பிடப்பட்ட அறுவடை', growthProgress: 'வளர்ச்சி முன்னேற்றம்',
    adjustFactors: 'காரணிகளை சரிசெய்க', yieldFactors: 'விளைச்சல் காரணிகள்',
    cropGrowthCalendar: 'பயிர் வளர்ச்சி காலண்டர்', historicalYield: 'வரலாற்று விளைச்சல் (டன்/எக்டர்)',
    fieldScouting: 'வயல் கண்காணிப்பு', newScoutReport: 'புதிய அறிக்கை',
    totalReports: 'மொத்த அறிக்கைகள்', highSeverity: 'அதிக தீவிரம்', fieldsScouted: 'கண்காணிக்கப்பட்ட வயல்கள்',
    field: 'வயல்', crop: 'பயிர்', latitude: 'அட்சரேகை', longitude: 'தீர்க்கரேகை',
    useGPS: 'GPS பயன்படுத்தவும்', severity: 'தீவிரம்',
    observations: 'கவனிப்புகள் மற்றும் குறிப்புகள்', uploadPhoto: 'புகைப்படம் பதிவேற்றவும்', saveReport: 'அறிக்கையை சேமிக்கவும்',
    scoutHistory: 'கண்காணிப்பு வரலாறு', low: 'குறைவு', medium: 'நடுத்தரம்', high: 'அதிகம்',
    smartAlertsTitle: 'ஸ்மார்ட் எச்சரிக்கைகள்', markAllRead: 'அனைத்தும் படித்ததாக குறிக்கவும்',
    disease: 'நோய்', weatherAlert: 'வானிலை', market: 'சந்தை', irrigation: 'நீர்ப்பாசனம்',
    resolveAlert: 'எச்சரிக்கையை தீர்க்கவும்', dismiss: 'நிராகரிக்கவும்', recommendedAction: 'பரிந்துரைக்கப்பட்ட நடவடிக்கை',
    agrobotTitle: 'AgroBot AI உதவியாளர்', agrobotSubtitle: 'BRICS வேளாண் தரவுகளில் பயிற்சி பெற்றது',
    newChat: 'புதிய அரட்டை', askAgrobot: 'AgroBot ஐ உங்கள் பண்ணையைப் பற்றி கேளுங்கள்...',
    agrobotDisclaimer: 'AgroBot AI வழிகாட்டுதல் வழங்குகிறது. முக்கியமான முடிவுகளுக்கு உள்ளூர் வேளாண் நிபுணரை அணுகவும்.',
    satelliteMapTitle: 'செயற்கைக்கோள் வரைபடம்', satelliteSubtitle: 'நேரலை NDVI மேலடுக்கு · Sentinel-2',
    avgFarmNdvi: 'சராசரி NDVI', totalFarmArea: 'மொத்த பண்ணை பரப்பு', activeStressZones: 'செயலில் உள்ள அழுத்த மண்டலங்கள்',
    offline: 'ஆஃப்லைன்', retry: 'மீண்டும் முயற்சிக்கவும்', loading: 'ஏற்றுகிறது...', noData: 'தரவு இல்லை', aboveAvg: 'பிராந்திய சராசரிக்கு மேல்',
    yourFarmingTechnique: 'உங்கள் வேளாண் நுட்பத்தை பகிரவும்', title: 'தலைப்பு', content: 'உள்ளடக்கம்', tags: 'குறிச்சொற்கள்',
  },

  ml: {
    appName: 'AgriN',
    appSubtitle: 'BRICS ഡിജിറ്റൽ നെറ്റ്‌വർക്ക്',
    overview: 'അവലോകനം',
    aiTools: 'AI ഉപകരണങ്ങൾ',
    farmIntelligence: 'കൃഷി ബുദ്ധി',
    marketsAndCommunity: 'വിപണിയും സമൂഹവും',
    settings: 'ക്രമീകരണങ്ങൾ',
    logout: 'ലോഗ് ഔട്ട്',
    loggedInAs: 'ലോഗിൻ ചെയ്തിരിക്കുന്നു',
    dashboard: 'ഡാഷ്‌ബോർഡ്',
    smartAlerts: 'സ്മാർട്ട് അലേർട്ടുകൾ',
    cropDiagnostics: 'വിള രോഗ നിർണ്ണയം',
    agroBot: 'AgroBot AI',
    satelliteMap: 'ഉപഗ്രഹ ഭൂപടം',
    weather: 'കാലാവസ്ഥ',
    yieldPredictor: 'വിളവ് പ്രവചനം',
    fieldScouting: 'ഫീൽഡ് സ്കൗട്ടിങ്',
    marketPrices: 'വിപണി വില',
    bricsExchange: 'BRICS അറിവ് കേന്ദ്രം',
    goodMorning: 'സുപ്രഭാതം',
    goodAfternoon: 'ഉച്ചയ്ക്ക് നമസ്കാരം',
    goodEvening: 'സന്ധ്യ നമസ്കാരം',
    farmer: 'കർഷകൻ',
    soilHealth: 'മണ്ണ് ആരോഗ്യം',
    optimal: 'അനുയോജ്യം',
    moisture: 'ഈർപ്പം',
    phLevel: 'pH നില',
    nitrogen: 'നൈട്രജൻ (N)',
    phosphorus: 'ഫോസ്ഫറസ് (P)',
    currentConditions: 'നിലവിലെ അവസ്ഥ',
    temperature: 'താപനില',
    humidity: 'ആർദ്രത',
    windSpeed: 'കാറ്റ് വേഗം',
    uvIndex: 'UV സൂചിക',
    farmOverview: 'ഫാം അവലോകനം',
    activeFields: 'സജീവ ഭൂമി',
    cropHealthAvg: 'വിള ആരോഗ്യ ശരാശരി',
    pendingAlerts: 'തീർക്കേണ്ട അലേർട്ടുകൾ',
    nextHarvest: 'അടുത്ത വിളവെടുപ്പ്',
    cropVigorNDVI: 'വിള ഊർജ്ജം (NDVI) — 6 ആഴ്ച',
    sentinelData: 'Sentinel-2 ഉപഗ്രഹ ഡേറ്റ',
    aiAdvisories: 'AI കൃഷി ഉപദേശം',
    coverCropping: 'കവർ ക്രോപ്പിങ് നിർദ്ദേശം',
    irrigationAlert: 'ജലസേചന അലേർട്ട്',
    welcomeBack: 'തിരിച്ചു സ്വാഗതം',
    signInAccount: 'നിങ്ങളുടെ അക്കൗണ്ടിൽ സൈൻ ഇൻ ചെയ്യുക',
    createAccount: 'അക്കൗണ്ട് ഉണ്ടാക്കുക',
    joinNetwork: 'BRICS കൃഷി നെറ്റ്‌വർക്കിൽ ചേരുക',
    email: 'ഇമെയിൽ',
    password: 'പാസ്‌വേഡ്',
    confirmPassword: 'പാസ്‌വേഡ് സ്ഥിരീകരിക്കുക',
    fullName: 'മുഴുവൻ പേര്',
    country: 'രാജ്യം',
    signIn: 'സൈൻ ഇൻ', register: 'രജിസ്റ്റർ', noAccount: 'അക്കൗണ്ട് ഇല്ലേ?', hasAccount: 'ഇതിനകം അക്കൗണ്ട് ഉണ്ടോ?',
    signingIn: 'സൈൻ ഇൻ ചെയ്യുന്നു...', registering: 'രജിസ്റ്റർ ചെയ്യുന്നു...',
    passwordStrength: 'പാസ്‌വേഡ് ശക്തി', weak: 'ദുർബലം', fair: 'ഭേദം', strong: 'ശക്തം', veryStrong: 'വളരെ ശക്തം',
    sevenDayForecast: '7-ദിവസ കാലാവസ്ഥ', precipitationProb: 'മഴ സാധ്യത (7 ദിവസം)',
    aiFarmSchedule: 'AI ഫാം ഷെഡ്യൂൾ', rainChance: 'മഴ സാധ്യത', wind: 'കാറ്റ്', refresh: 'പുതുക്കുക',
    knowledgeExchange: 'അറിവ് കൈമാറ്റം', shareKnowledge: 'അറിവ് പങ്കിടുക',
    publishToBrics: 'BRICS നെറ്റ്‌വർക്കിൽ പ്രസിദ്ധീകരിക്കുക', searchTechniques: 'സാങ്കേതിക വിദ്യകൾ തിരയുക...',
    cancel: 'റദ്ദാക്കുക', replies: 'മറുപടികൾ', autoTranslated: 'സ്വയം വിവർത്തനം',
    marketPricesTitle: 'വിപണി വില', refreshPrices: 'വില പുതുക്കുക', lastUpdated: 'അവസാനം അപ്‌ഡേറ്റ്',
    sellNow: 'ഇപ്പോൾ വിൽക്കുക', hold: 'കാത്തിരിക്കുക', buyDip: 'വാങ്ങുക', aiSignal: 'AI സൂചന',
    yieldPredictorTitle: 'വിളവ് പ്രവചനം', tonsPerHa: 'ടൺ/ഹെക്ടർ',
    confidence: 'ആത്മവിശ്വാസം', estHarvest: 'കണക്കാക്കിയ വിളവെടുപ്പ്', growthProgress: 'വളർച്ചാ പുരോഗതി',
    adjustFactors: 'ഘടകങ്ങൾ ക്രമീകരിക്കുക', yieldFactors: 'വിളവ് ഘടകങ്ങൾ',
    cropGrowthCalendar: 'വിള വളർച്ചാ കലണ്ടർ', historicalYield: 'ചരിത്രപരമായ വിളവ് (ടൺ/ഹെക്ടർ)',
    fieldScouting: 'ഫീൽഡ് സ്കൗട്ടിങ്', newScoutReport: 'പുതിയ റിപ്പോർട്ട്',
    totalReports: 'ആകെ റിപ്പോർട്ടുകൾ', highSeverity: 'ഉയർന്ന തീവ്രത', fieldsScouted: 'സ്കൗട്ട് ചെയ്ത ഭൂമി',
    field: 'ഭൂമി', crop: 'വിള', latitude: 'അക്ഷാംശം', longitude: 'രേഖാംശം',
    useGPS: 'GPS ഉപയോഗിക്കുക', severity: 'തീവ്രത',
    observations: 'നിരീക്ഷണങ്ങളും കുറിപ്പുകളും', uploadPhoto: 'ഫോട്ടോ അപ്‌ലോഡ് ചെയ്യുക', saveReport: 'റിപ്പോർട്ട് സൂക്ഷിക്കുക',
    scoutHistory: 'സ്കൗട്ടിങ് ചരിത്രം', low: 'കുറവ്', medium: 'മധ്യം', high: 'ഉയർന്നത്',
    smartAlertsTitle: 'സ്മാർട്ട് അലേർട്ടുകൾ', markAllRead: 'എല്ലാം വായിച്ചതായി അടയാളപ്പെടുത്തുക',
    disease: 'രോഗം', weatherAlert: 'കാലാവസ്ഥ', market: 'വിപണി', irrigation: 'ജലസേചനം',
    resolveAlert: 'അലേർട്ട് പരിഹരിക്കുക', dismiss: 'നിരസിക്കുക', recommendedAction: 'ശുപാർശ ചെയ്ത നടപടി',
    agrobotTitle: 'AgroBot AI സഹായി', agrobotSubtitle: 'BRICS കൃഷി ഡേറ്റസെറ്റിൽ പരിശീലനം',
    newChat: 'പുതിയ ചാറ്റ്', askAgrobot: 'AgroBot നോട് നിങ്ങളുടെ ഫാമിനെ കുറിച്ച് ചോദിക്കുക...',
    agrobotDisclaimer: 'AgroBot AI മാർഗ്ഗനിർദ്ദേശം നൽകുന്നു. പ്രധാന തീരുമാനങ്ങൾക്ക് പ്രാദേശിക കൃഷി വിദഗ്ദ്ധനെ സമീപിക്കുക.',
    satelliteMapTitle: 'ഉപഗ്രഹ ഭൂപടം', satelliteSubtitle: 'തത്സമയ NDVI ഓവർലേ · Sentinel-2',
    avgFarmNdvi: 'ശരാശരി NDVI', totalFarmArea: 'ആകെ ഫാം വിസ്തൃതി', activeStressZones: 'സജീവ സ്ട്രെസ് സോണുകൾ',
    offline: 'ഓഫ്‌ലൈൻ', retry: 'വീണ്ടും ശ്രമിക്കുക', loading: 'ലോഡ് ചെയ്യുന്നു...', noData: 'ഡേറ്റ ഇല്ല', aboveAvg: 'പ്രാദേശിക ശരാശരിക്ക് മുകളിൽ',
    yourFarmingTechnique: 'നിങ്ങളുടെ കൃഷി സാങ്കേതിക വിദ്യ പങ്കിടുക', title: 'തലക്കെട്ട്', content: 'ഉള്ളടക്കം', tags: 'ടാഗുകൾ',
  },

  mr: {
    appName: 'AgriN',
    appSubtitle: 'BRICS डिजिटल नेटवर्क',
    overview: 'आढावा',
    aiTools: 'AI साधने',
    farmIntelligence: 'शेती बुद्धिमत्ता',
    marketsAndCommunity: 'बाजार आणि समुदाय',
    settings: 'सेटिंग्ज',
    logout: 'बाहेर पडा',
    loggedInAs: 'लॉग इन आहे',
    dashboard: 'डॅशबोर्ड',
    smartAlerts: 'स्मार्ट सूचना',
    cropDiagnostics: 'पिक निदान',
    agroBot: 'AgroBot AI',
    satelliteMap: 'उपग्रह नकाशा',
    weather: 'हवामान',
    yieldPredictor: 'उत्पन्न अंदाज',
    fieldScouting: 'शेत सर्वेक्षण',
    marketPrices: 'बाजारभाव',
    bricsExchange: 'BRICS ज्ञान केंद्र',
    goodMorning: 'सुप्रभात',
    goodAfternoon: 'शुभ दुपार',
    goodEvening: 'शुभ संध्याकाळ',
    farmer: 'शेतकरी',
    soilHealth: 'माती आरोग्य',
    optimal: 'सर्वोत्तम',
    moisture: 'ओलावा',
    phLevel: 'pH पातळी',
    nitrogen: 'नायट्रोजन (N)',
    phosphorus: 'फॉस्फरस (P)',
    currentConditions: 'सध्याची परिस्थिती',
    temperature: 'तापमान',
    humidity: 'आर्द्रता',
    windSpeed: 'वाऱ्याचा वेग',
    uvIndex: 'UV निर्देशांक',
    farmOverview: 'शेत आढावा',
    activeFields: 'सक्रिय शेते',
    cropHealthAvg: 'पिक आरोग्य सरासरी',
    pendingAlerts: 'प्रलंबित सूचना',
    nextHarvest: 'पुढील कापणी',
    cropVigorNDVI: 'पिक जोम (NDVI) — 6 आठवडे',
    sentinelData: 'Sentinel-2 उपग्रह डेटा',
    aiAdvisories: 'AI शेती सल्ला',
    coverCropping: 'आच्छादन पिकाची सूचना',
    irrigationAlert: 'सिंचन सूचना',
    welcomeBack: 'परत स्वागत आहे',
    signInAccount: 'आपल्या खात्यात साइन इन करा',
    createAccount: 'खाते तयार करा',
    joinNetwork: 'BRICS कृषी नेटवर्कमध्ये सामील व्हा',
    email: 'ईमेल', password: 'पासवर्ड', confirmPassword: 'पासवर्ड पुष्टी करा',
    fullName: 'पूर्ण नाव', country: 'देश',
    signIn: 'साइन इन', register: 'नोंदणी', noAccount: 'खाते नाही का?', hasAccount: 'आधीच खाते आहे का?',
    signingIn: 'साइन इन होत आहे...', registering: 'नोंदणी होत आहे...',
    passwordStrength: 'पासवर्ड शक्ती', weak: 'कमकुवत', fair: 'ठीक', strong: 'मजबूत', veryStrong: 'अतिशय मजबूत',
    sevenDayForecast: '7-दिवस अंदाज', precipitationProb: 'पाऊस शक्यता (7 दिवस)',
    aiFarmSchedule: 'AI शेती वेळापत्रक', rainChance: 'पावसाची शक्यता', wind: 'वारा', refresh: 'ताजे करा',
    knowledgeExchange: 'ज्ञान देवाणघेवाण', shareKnowledge: 'ज्ञान सामायिक करा',
    publishToBrics: 'BRICS नेटवर्कवर प्रकाशित करा', searchTechniques: 'तंत्रे शोधा...',
    cancel: 'रद्द करा', replies: 'उत्तरे', autoTranslated: 'स्वयं-अनुवादित',
    marketPricesTitle: 'बाजारभाव', refreshPrices: 'भाव ताजे करा', lastUpdated: 'शेवटचे अपडेट',
    sellNow: 'आत्ता विका', hold: 'थांबा', buyDip: 'खरेदी करा', aiSignal: 'AI संकेत',
    yieldPredictorTitle: 'उत्पन्न अंदाज', tonsPerHa: 'टन/हेक्टर',
    confidence: 'विश्वास', estHarvest: 'अंदाजित कापणी', growthProgress: 'वाढ प्रगती',
    adjustFactors: 'घटक समायोजित करा', yieldFactors: 'उत्पन्न घटक',
    cropGrowthCalendar: 'पिक वाढ दिनदर्शिका', historicalYield: 'ऐतिहासिक उत्पन्न (टन/हेक्टर)',
    fieldScouting: 'शेत सर्वेक्षण', newScoutReport: 'नवीन अहवाल',
    totalReports: 'एकूण अहवाल', highSeverity: 'उच्च तीव्रता', fieldsScouted: 'सर्वेक्षण केलेली शेते',
    field: 'शेत', crop: 'पिक', latitude: 'अक्षांश', longitude: 'रेखांश',
    useGPS: 'GPS वापरा', severity: 'तीव्रता',
    observations: 'निरीक्षणे आणि टिपणी', uploadPhoto: 'फोटो अपलोड करा', saveReport: 'अहवाल जतन करा',
    scoutHistory: 'सर्वेक्षण इतिहास', low: 'कमी', medium: 'मध्यम', high: 'उच्च',
    smartAlertsTitle: 'स्मार्ट सूचना', markAllRead: 'सर्व वाचलेले चिन्हांकित करा',
    disease: 'रोग', weatherAlert: 'हवामान', market: 'बाजार', irrigation: 'सिंचन',
    resolveAlert: 'सूचना सोडवा', dismiss: 'नाकारा', recommendedAction: 'शिफारस केलेली कृती',
    agrobotTitle: 'AgroBot AI सहाय्यक', agrobotSubtitle: 'BRICS कृषी डेटासेटवर प्रशिक्षित',
    newChat: 'नवीन चॅट', askAgrobot: 'AgroBot ला आपल्या शेताबद्दल काहीही विचारा...',
    agrobotDisclaimer: 'AgroBot AI मार्गदर्शन प्रदान करते. महत्त्वाच्या निर्णयांसाठी स्थानिक कृषी तज्ज्ञाशी सल्लामसलत करा.',
    satelliteMapTitle: 'उपग्रह नकाशा', satelliteSubtitle: 'रिअल-टाइम NDVI ओव्हरले · Sentinel-2',
    avgFarmNdvi: 'सरासरी NDVI', totalFarmArea: 'एकूण शेत क्षेत्र', activeStressZones: 'सक्रिय ताण क्षेत्र',
    offline: 'ऑफलाइन', retry: 'पुन्हा प्रयत्न', loading: 'लोड होत आहे...', noData: 'डेटा उपलब्ध नाही', aboveAvg: 'प्रादेशिक सरासरीपेक्षा वर',
    yourFarmingTechnique: 'आपले शेती तंत्र सामायिक करा', title: 'शीर्षक', content: 'सामग्री', tags: 'टॅग',
    whatShouldIDoToday: 'आज मी काय करावे?',
    whatShouldIDoTodayDesc: 'अलीकडील हवामान आणि आपल्या पीक चक्रानुसार, ही सर्वात महत्त्वाची कृती आहे.',
    sprayFungicideNow: 'आता बुरशीनाशक फवारा',
    highHumidityExpected: 'उद्या उच्च आर्द्रता (+80%) अपेक्षित आहे. पानांच्या करपापासून बचाव करा.',
    viewDetails: 'तपशील पहा',
    verified: 'सत्यापित',
    usedSuccessfullyByFarmers: 'या हंगामात आपल्या ब्लॉकमधील ४७ शेतकऱ्यांनी यशस्वीरित्या वापरले.',
    sprayFungicideNowDesc: 'अलीकडील हवामान आणि आपल्या पीक चक्रानुसार, ही सर्वात महत्त्वाची कृती आहे. उद्या पाऊस सुरू होण्यापूर्वी आज बुरशीनाशक फवारा.',
    financialServices: 'आर्थिक सेवा',
    laborAndEquipment: 'मजूर आणि उपकरणे',
    seedsAndInputs: 'बियाणे आणि खते',
    postHarvest: 'काढणीपश्चात',
    transitionSupport: 'संक्रमण समर्थन',
    womenFarmers: 'महिला शेतकरी',
    govtSchemes: 'सरकारी योजना',
    communityAndTrust: 'समुदाय आणि विश्वास',
    offlineMode: 'ऑफलाइन मोड',
    syncQueueManager: 'सिंक रांग व्यवस्थापक',
    smsAndUssdLite: 'SMS आणि USSD लाइट',
    dataPrivacyAndBrics: 'डेटा गोपनीयता आणि BRICS',
    batterySaver: 'बॅटरी सेव्हर',
    progressiveBundles: 'प्रोग्रेसिव्ह बंडल',
    farmerServices: 'शेतकरी सेवा',
    supportAndCommunity: 'समर्थन आणि समुदाय',
    marketRatesCropNews: 'बाजारभाव आणि पीक बातम्या',
    realTimeMandiRates: 'रिअल-टाइम मंडी भाव',
    realTimeCropNews: 'रिअल-टाइम पीक आणि मंडी बातम्या',
    liveLocationNewsAdvisories: 'थेट स्थान-आधारित कृषी बातम्या आणि अधिकृत सूचना',
    localPeerProof: 'स्थानिक शेतकरी अनुभव',
    similarFarms: 'तुमच्यासारखीच शेते',
    creditLoanMatching: 'क्रेडिट आणि कर्ज जुळवणी',
    personalizedFinancing: 'तुमच्या शेत प्रोफाइल आणि स्थानाशी जुळणारे वैयक्तिकृत वित्तपोषण पर्याय.',
    maxAmount: 'कमाल रक्कम',
    interestRate: 'व्याजदर',
    processing: 'प्रक्रिया',
    days: 'दिवस',
  },

  te: {
    appName: 'AgriN',
    appSubtitle: 'BRICS డిజిటల్ నెట్‌వర్క్',
    overview: 'అవలోకనం',
    aiTools: 'AI సాధనాలు',
    farmIntelligence: 'వ్యవసాయ మేధస్సు',
    marketsAndCommunity: 'మార్కెట్ మరియు సమాజం',
    settings: 'సెట్టింగులు',
    logout: 'లాగ్ అవుట్',
    loggedInAs: 'లాగిన్ అయ్యారు',
    dashboard: 'డాష్‌బోర్డ్',
    smartAlerts: 'స్మార్ట్ హెచ్చరికలు',
    cropDiagnostics: 'పంట వ్యాధి నిర్ధారణ',
    agroBot: 'AgroBot AI',
    satelliteMap: 'ఉపగ్రహ మ్యాప్',
    weather: 'వాతావరణం',
    yieldPredictor: 'దిగుబడి అంచనా',
    fieldScouting: 'పొలం సర్వే',
    marketPrices: 'మార్కెట్ ధరలు',
    bricsExchange: 'BRICS జ్ఞాన కేంద్రం',
    goodMorning: 'శుభోదయం',
    goodAfternoon: 'శుభ మధ్యాహ్నం',
    goodEvening: 'శుభ సాయంత్రం',
    farmer: 'రైతు',
    soilHealth: 'నేల ఆరోగ్యం',
    optimal: 'అనువైనది',
    moisture: 'తేమ',
    phLevel: 'pH స్థాయి',
    nitrogen: 'నైట్రోజన్ (N)',
    phosphorus: 'ఫాస్ఫరస్ (P)',
    currentConditions: 'ప్రస్తుత పరిస్థితులు',
    temperature: 'ఉష్ణోగ్రత',
    humidity: 'తేమ',
    windSpeed: 'గాలి వేగం',
    uvIndex: 'UV సూచిక',
    farmOverview: 'వ్యవసాయ అవలోకనం',
    activeFields: 'చురుకైన పొలాలు',
    cropHealthAvg: 'పంట ఆరోగ్య సగటు',
    pendingAlerts: 'పెండింగ్ హెచ్చరికలు',
    nextHarvest: 'తదుపరి కోత',
    cropVigorNDVI: 'పంట శక్తి (NDVI) — 6 వారాలు',
    sentinelData: 'Sentinel-2 ఉపగ్రహ డేటా',
    aiAdvisories: 'AI వ్యవసాయ సలహాలు',
    coverCropping: 'కవర్ క్రాపింగ్ సూచన',
    irrigationAlert: 'నీటి పారుదల హెచ్చరిక',
    welcomeBack: 'తిరిగి స్వాగతం',
    signInAccount: 'మీ ఖాతాలో సైన్ ఇన్ చేయండి',
    createAccount: 'ఖాతా సృష్టించండి',
    joinNetwork: 'BRICS వ్యవసాయ నెట్‌వర్క్‌లో చేరండి',
    email: 'ఇమెయిల్', password: 'పాస్‌వర్డ్', confirmPassword: 'పాస్‌వర్డ్ నిర్ధారించండి',
    fullName: 'పూర్తి పేరు', country: 'దేశం',
    signIn: 'సైన్ ఇన్', register: 'నమోదు', noAccount: 'ఖాతా లేదా?', hasAccount: 'ఇప్పటికే ఖాతా ఉందా?',
    signingIn: 'సైన్ ఇన్ అవుతోంది...', registering: 'నమోదు అవుతోంది...',
    passwordStrength: 'పాస్‌వర్డ్ శక్తి', weak: 'బలహీనం', fair: 'సాధారణం', strong: 'బలంగా', veryStrong: 'చాలా బలంగా',
    sevenDayForecast: '7-రోజుల అంచనా', precipitationProb: 'వర్షపాత సంభావ్యత (7 రోజులు)',
    aiFarmSchedule: 'AI వ్యవసాయ షెడ్యూల్', rainChance: 'వర్షం అవకాశం', wind: 'గాలి', refresh: 'రిఫ్రెష్ చేయండి',
    knowledgeExchange: 'జ్ఞాన మార్పిడి', shareKnowledge: 'జ్ఞానాన్ని పంచండి',
    publishToBrics: 'BRICS నెట్‌వర్క్‌లో ప్రచురించండి', searchTechniques: 'సాంకేతికతలు వెతకండి...',
    cancel: 'రద్దు చేయండి', replies: 'సమాధానాలు', autoTranslated: 'స్వయంచాలకంగా అనువదించబడింది',
    marketPricesTitle: 'మార్కెట్ ధరలు', refreshPrices: 'ధరలు రిఫ్రెష్ చేయండి', lastUpdated: 'చివరి నవీకరణ',
    sellNow: 'ఇప్పుడు అమ్మండి', hold: 'వేచి ఉండండి', buyDip: 'కొనుగోలు చేయండి', aiSignal: 'AI సంకేతం',
    yieldPredictorTitle: 'దిగుబడి అంచనా', tonsPerHa: 'టన్నులు/హెక్టార్',
    confidence: 'విశ్వాసం', estHarvest: 'అంచనా కోత', growthProgress: 'వృద్ధి పురోగతి',
    adjustFactors: 'కారకాలను సర్దుబాటు చేయండి', yieldFactors: 'దిగుబడి కారకాలు',
    cropGrowthCalendar: 'పంట వృద్ధి క్యాలెండర్', historicalYield: 'చారిత్రక దిగుబడి (టన్నులు/హెక్టార్)',
    fieldScouting: 'పొలం సర్వే', newScoutReport: 'కొత్త నివేదిక',
    totalReports: 'మొత్తం నివేదికలు', highSeverity: 'అధిక తీవ్రత', fieldsScouted: 'సర్వే చేసిన పొలాలు',
    field: 'పొలం', crop: 'పంట', latitude: 'అక్షాంశం', longitude: 'రేఖాంశం',
    useGPS: 'GPS వాడండి', severity: 'తీవ్రత',
    observations: 'పరిశీలనలు మరియు గమనికలు', uploadPhoto: 'ఫోటో అప్‌లోడ్ చేయండి', saveReport: 'నివేదిక సేవ్ చేయండి',
    scoutHistory: 'సర్వే చరిత్ర', low: 'తక్కువ', medium: 'మధ్యస్థం', high: 'అధికం',
    smartAlertsTitle: 'స్మార్ట్ హెచ్చరికలు', markAllRead: 'అన్నీ చదివినట్లు గుర్తించండి',
    disease: 'వ్యాధి', weatherAlert: 'వాతావరణం', market: 'మార్కెట్', irrigation: 'నీటి పారుదల',
    resolveAlert: 'హెచ్చరిక పరిష్కరించండి', dismiss: 'తిరస్కరించండి', recommendedAction: 'సిఫార్సు చేసిన చర్య',
    agrobotTitle: 'AgroBot AI సహాయకుడు', agrobotSubtitle: 'BRICS వ్యవసాయ డేటాసెట్‌పై శిక్షణ పొందినది',
    newChat: 'కొత్త చాట్', askAgrobot: 'మీ పొలం గురించి AgroBot ని అడగండి...',
    agrobotDisclaimer: 'AgroBot AI మార్గదర్శకత్వం అందిస్తుంది. ముఖ్యమైన నిర్ణయాల కోసం స్థానిక వ్యవసాయ నిపుణుడిని సంప్రదించండి.',
    satelliteMapTitle: 'ఉపగ్రహ మ్యాప్', satelliteSubtitle: 'నిజ-సమయ NDVI ఓవర్లే · Sentinel-2',
    avgFarmNdvi: 'సగటు NDVI', totalFarmArea: 'మొత్తం వ్యవసాయ విస్తీర్ణం', activeStressZones: 'చురుకైన ఒత్తిడి మండలాలు',
    offline: 'ఆఫ్‌లైన్', retry: 'మళ్ళీ ప్రయత్నించండి', loading: 'లోడ్ అవుతోంది...', noData: 'డేటా లేదు', aboveAvg: 'ప్రాంతీయ సగటుకు పైగా',
    yourFarmingTechnique: 'మీ వ్యవసాయ సాంకేతికతను పంచండి', title: 'శీర్షిక', content: 'కంటెంట్', tags: 'ట్యాగ్‌లు',
  },
  kn: {
    appName: 'AgriN',
    appSubtitle: 'BRICS ಡಿಜಿಟಲ್ ನೆಟ್‌ವರ್ಕ್',
    overview: 'ಅವಲೋಕನ',
    aiTools: 'AI ಪರಿಕರಗಳು',
    farmIntelligence: 'ಕೃಷಿ ಬುದ್ಧಿಮತ್ತೆ',
    marketsAndCommunity: 'ಮಾರುಕಟ್ಟೆ ಮತ್ತು ಸಮುದಾಯ',
    settings: 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    logout: 'ಲಾಗ್‌ಔಟ್',
    loggedInAs: 'ಲಾಗಿನ್:',
    dashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    smartAlerts: 'ಸ್ಮಾರ್ಟ್ ಎಚ್ಚರಿಕೆಗಳು',
    cropDiagnostics: 'ಬೆಳೆ ರೋಗನಿರ್ಣಯ',
    agroBot: 'ಅಗ್ರೋಬಾಟ್ AI',
    satelliteMap: 'ಉಪಗ್ರಹ ನಕ್ಷೆ',
    weather: 'ಹವಾಮಾನ',
    yieldPredictor: 'ಇಳುವರಿ ಮುನ್ಸೂಚನೆ',
    fieldScouting: 'ಹೊಲ ಸಮೀಕ್ಷೆ',
    marketPrices: 'ಮಾರುಕಟ್ಟೆ ಬೆಲೆ',
    bricsExchange: 'ಜ್ಞಾನ ವಿನಿಮಯ',
    goodMorning: 'ಶುಭ ಬೆಳಿಗ್ಗೆ',
    goodAfternoon: 'ಶುಭ ಮಧ್ಯಾಹ್ನ',
    goodEvening: 'ಶುಭ ಸಂಜೆ',
    farmer: 'ರೈತ',
    soilHealth: 'ಮಣ್ಣಿನ ಆರೋಗ್ಯ',
    optimal: 'ಅತ್ಯುತ್ತಮ',
    moisture: 'ತೇವಾಂಶ',
    phLevel: 'pH ಮಟ್ಟ',
    nitrogen: 'ಸಾರಜನಕ (N)',
    phosphorus: 'ರಂಜಕ (P)',
    currentConditions: 'ಪ್ರಸ್ತುತ ಸ್ಥಿತಿ',
    temperature: 'ತಾಪಮಾನ',
    humidity: 'ಆರ್ದ್ರತೆ',
    windSpeed: 'ಗಾಳಿ ವೇಗ',
    uvIndex: 'UV ಸೂಚ್ಯಂಕ',
    farmOverview: 'ಹೊಲದ ಅವಲೋಕನ',
    activeFields: 'ಸಕ್ರಿಯ ಹೊಲಗಳು',
    cropHealthAvg: 'ಬೆಳೆ ಆರೋಗ್ಯ ಸರಾಸರಿ',
    pendingAlerts: 'ಬಾಕಿ ಎಚ್ಚರಿಕೆಗಳು',
    nextHarvest: 'ಮುಂದಿನ ಕೊಯ್ಲು',
    cropVigorNDVI: 'ಬೆಳೆ ಬೆಳವಣಿಗೆ (NDVI)',
    sentinelData: 'Sentinel-2 ಡೇಟಾ',
    aiAdvisories: 'AI ಸಲಹೆ',
    coverCropping: 'ಹೊದಿಕೆ ಬೆಳೆ ಶಿಫಾರಸು',
    irrigationAlert: 'ನೀರಾವರಿ ಎಚ್ಚರಿಕೆ',
    welcomeBack: 'ಪುನಃ ಸ್ವಾಗತ',
    signInAccount: 'ಖಾತೆಗೆ ಸೈನ್ ಇನ್ ಮಾಡಿ',
    createAccount: 'ಖಾತೆ ರಚಿಸಿ',
    joinNetwork: 'BRICS ಕೃಷಿ ಜಾಲಕ್ಕೆ ಸೇರಿ',
    email: 'ಇಮೇಲ್',
    password: 'ಪಾಸ್‌ವರ್ಡ್',
    confirmPassword: 'ಪಾಸ್‌ವರ್ಡ್ ದೃಢೀಕರಿಸಿ',
    fullName: 'ಪೂರ್ಣ ಹೆಸರು',
    country: 'ದೇಶ',
    signIn: 'ಸೈನ್ ಇನ್',
    register: 'ನೋಂದಣಿ',
    noAccount: 'ಖಾತೆ ಇಲ್ಲವೇ?',
    hasAccount: 'ಖಾತೆ ಇದೆಯೇ?',
    signingIn: 'ಸೈನ್ ಇನ್ ಆಗುತ್ತಿದೆ...',
    registering: 'ನೋಂದಣಿ ಆಗುತ್ತಿದೆ...',
    passwordStrength: 'ಪಾಸ್‌ವರ್ಡ್ ಶಕ್ತಿ',
    weak: 'ದುರ್ಬಲ',
    fair: 'ಸಾಧಾರಣ',
    strong: 'ಬಲವಾದ',
    veryStrong: 'ಅತಿ ಬಲವಾದ',
    sevenDayForecast: '೭-ದಿನಗಳ ಮುನ್ಸೂಚನೆ',
    precipitationProb: 'ಮಳೆಯ ಸಾಧ್ಯತೆ',
    aiFarmSchedule: 'AI ಕೃಷಿ ವೇಳಾಪಟ್ಟಿ',
    rainChance: 'ಮಳೆ ಸಾಧ್ಯತೆ',
    wind: 'ಗಾಳಿ',
    refresh: 'ರಿಫ್ರೆಶ್',
    knowledgeExchange: 'ಜ್ಞಾನ ವಿನಿಮಯ',
    shareKnowledge: 'ಜ್ಞಾನ ಹಂಚಿ',
    publishToBrics: 'ಪ್ರಕಟಿಸಿ',
    searchTechniques: 'ತಂತ್ರಗಳನ್ನು ಹುಡುಕಿ...',
    cancel: 'ರದ್ದು',
    replies: 'ಉತ್ತರಗಳು',
    autoTranslated: 'ಸ್ವಯಂ-ಅನುವಾದಿತ',
    marketPricesTitle: 'ಮಾರುಕಟ್ಟೆ ಬೆಲೆ',
    refreshPrices: 'ಬೆಲೆ ರಿಫ್ರೆಶ್',
    lastUpdated: 'ಕೊನೆಯ ನವೀಕರಣ',
    sellNow: 'ಈಗ ಮಾರಿ',
    hold: 'ಹಿಡಿದಿಡಿ',
    buyDip: 'ಖರೀದಿಸಿ',
    aiSignal: 'AI ಸಂಕೇತ',
    yieldPredictorTitle: 'ಇಳುವರಿ ಮುನ್ಸೂಚನೆ',
    tonsPerHa: 'ಟನ್/ಹೆಕ್ಟೇರ್',
    confidence: 'ವಿಶ್ವಾಸ',
    estHarvest: 'ಅಂದಾಜಿತ ಕೊಯ್ಲು',
    growthProgress: 'ಬೆಳವಣಿಗೆ ಪ್ರಗತಿ',
    adjustFactors: 'ಅಂಶಗಳನ್ನು ಹೊಂದಿಸಿ',
    yieldFactors: 'ಇಳುವರಿ ಅಂಶಗಳು',
    cropGrowthCalendar: 'ಬೆಳೆ ಬೆಳವಣಿಗೆ ಕ್ಯಾಲೆಂಡರ್',
    historicalYield: 'ಐತಿಹಾಸಿಕ ಇಳುವರಿ (ಟನ್/ಹೆ)',
    newScoutReport: 'ಹೊಸ ವರದಿ',
    totalReports: 'ಒಟ್ಟು ವರದಿಗಳು',
    highSeverity: 'ಹೆಚ್ಚಿನ ತೀವ್ರತೆ',
    fieldsScouted: 'ಸಮೀಕ್ಷಿತ ಹೊಲಗಳು',
    field: 'ಹೊಲ',
    crop: 'ಬೆಳೆ',
    latitude: 'ಅಕ್ಷಾಂಶ',
    longitude: 'ರೇಖಾಂಶ',
    useGPS: 'GPS ಬಳಸಿ',
    severity: 'ತೀವ್ರತೆ',
    observations: 'ಅವಲೋಕನಗಳು',
    uploadPhoto: 'ಫೋಟೋ ಅಪ್‌ಲೋಡ್',
    saveReport: 'ವರದಿ ಉಳಿಸಿ',
    scoutHistory: 'ಸಮೀಕ್ಷೆ ಇತಿಹಾಸ',
    low: 'ಕಡಿಮೆ',
    medium: 'ಮಧ್ಯಮ',
    high: 'ಹೆಚ್ಚು',
    smartAlertsTitle: 'ಸ್ಮಾರ್ಟ್ ಎಚ್ಚರಿಕೆಗಳು',
    markAllRead: 'ಎಲ್ಲಾ ಓದಿದಂತೆ ಗುರುತಿಸಿ',
    disease: 'ರೋಗ',
    weatherAlert: 'ಹವಾಮಾನ',
    market: 'ಮಾರುಕಟ್ಟೆ',
    irrigation: 'ನೀರಾವರಿ',
    resolveAlert: 'ಎಚ್ಚರಿಕೆ ಪರಿಹರಿಸಿ',
    dismiss: 'ತೆಗೆದುಹಾಕಿ',
    recommendedAction: 'ಶಿಫಾರಸು ಮಾಡಿದ ಕ್ರಮ',
    agrobotTitle: 'ಅಗ್ರೋಬಾಟ್ AI ಸಹಾಯಕ',
    agrobotSubtitle: 'BRICS ಡೇಟಾಸೆಟ್‌ನಲ್ಲಿ ತರಬೇತಿ',
    newChat: 'ಹೊಸ ಚಾಟ್',
    askAgrobot: 'ನಿಮ್ಮ ಕೃಷಿ ಬಗ್ಗೆ ಅಗ್ರೋಬಾಟ್‌ಗೆ ಕೇಳಿ...',
    agrobotDisclaimer: 'ಅಗ್ರೋಬಾಟ್ AI ಮಾರ್ಗದರ್ಶನ ನೀಡುತ್ತದೆ. ಮಹತ್ವದ ನಿರ್ಧಾರಗಳಿಗೆ ಸ್ಥಳೀಯ ತಜ್ಞರನ್ನು ಸಂಪರ್ಕಿಸಿ.',
    satelliteMapTitle: 'ಉಪಗ್ರಹ ನಕ್ಷೆ',
    satelliteSubtitle: 'ರಿಯಲ್-ಟೈಮ್ NDVI · Sentinel-2',
    avgFarmNdvi: 'ಸರಾಸರಿ NDVI',
    totalFarmArea: 'ಒಟ್ಟು ಕೃಷಿ ಪ್ರದೇಶ',
    activeStressZones: 'ಸಕ್ರಿಯ ಒತ್ತಡ ವಲಯ',
    offline: 'ಆಫ್‌ಲೈನ್',
    retry: 'ಮರುಪ್ರಯತ್ನಿಸಿ',
    loading: 'ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
    noData: 'ಡೇಟಾ ಇಲ್ಲ',
    aboveAvg: 'ಪ್ರಾದೇಶಿಕ ಸರಾಸರಿಗಿಂತ ಮೇಲೆ',
    yourFarmingTechnique: 'ನಿಮ್ಮ ಕೃಷಿ ತಂತ್ರ ಹಂಚಿ',
    title: 'ಶೀರ್ಷಿಕೆ',
    content: 'ವಿಷಯ',
    tags: 'ಟ್ಯಾಗ್‌ಗಳು',
    whatShouldIDoToday: 'ನಾನು ಇಂದು ಏನು ಮಾಡಬೇಕು?',
    whatShouldIDoTodayDesc: 'ಹವಾಮಾನ ಮತ್ತು ಬೆಳೆ ಚಕ್ರದ ಆಧಾರದ ಮೇಲೆ, ಇದು ಅತ್ಯಂತ ಮಹತ್ವದ ಕ್ರಮ.',
    sprayFungicideNow: 'ಈಗ ಶಿಲೀಂಧ್ರನಾಶಕ ಸಿಂಪಡಿಸಿ',
    highHumidityExpected: 'ನಾಳೆ ಹೆಚ್ಚಿನ ಆರ್ದ್ರತೆ ನಿರೀಕ್ಷಿತ. ಎಲೆ ಒಣಗುವಿಕೆ ತಡೆಯಿರಿ.',
    viewDetails: 'ವಿವರ ನೋಡಿ',
    verified: 'ಪರಿಶೀಲಿಸಲಾಗಿದೆ',
    usedSuccessfullyByFarmers: 'ನಿಮ್ಮ ಪ್ರದೇಶದಲ್ಲಿ 47 ರೈತರು ಯಶಸ್ವಿಯಾಗಿ ಬಳಸಿದ್ದಾರೆ.',
    sprayFungicideNowDesc: 'ಹವಾಮಾನ ಮತ್ತು ಬೆಳೆ ಚಕ್ರದ ಆಧಾರದ ಮೇಲೆ ಇದು ಅತ್ಯಂತ ಮಹತ್ವದ ಕ್ರಮ.',
    financialServices: 'ಹಣಕಾಸು ಸೇವೆಗಳು',
    laborAndEquipment: 'ಕಾರ್ಮಿಕ ಮತ್ತು ಉಪಕರಣ',
    seedsAndInputs: 'ಬೀಜ ಮತ್ತು ಒಳಹರಿವು',
    postHarvest: 'ಕೊಯ್ಲಿನ ನಂತರದ ನಿರ್ವಹಣೆ',
    transitionSupport: 'ಪರಿವರ್ತನೆ ಬೆಂಬಲ',
    womenFarmers: 'ಮಹಿಳಾ ರೈತರು',
    govtSchemes: 'ಸರ್ಕಾರಿ ಯೋಜನೆಗಳು',
    communityAndTrust: 'ಸಮುದಾಯ ಮತ್ತು ನಂಬಿಕೆ',
    offlineMode: 'ಆಫ್‌ಲೈನ್ ಮೋಡ್',
    syncQueueManager: 'ಸಿಂಕ್ ಕ್ಯೂ ನಿರ್ವಾಹಕ',
    smsAndUssdLite: 'SMS ಮತ್ತು USSD ಲೈಟ್',
    dataPrivacyAndBrics: 'ಡೇಟಾ ಗೌಪ್ಯತೆ',
    batterySaver: 'ಬ್ಯಾಟರಿ ಸೇವರ್',
    progressiveBundles: 'ಪ್ರಗತಿಶೀಲ ಬಂಡಲ್',
    farmerServices: 'ರೈತ ಸೇವೆಗಳು',
    supportAndCommunity: 'ಬೆಂಬಲ ಮತ್ತು ಸಮುದಾಯ',
    marketRatesCropNews: 'ಮಾರುಕಟ್ಟೆ ದರ ಮತ್ತು ಬೆಳೆ ಸುದ್ದಿ',
    realTimeMandiRates: 'ರಿಯಲ್-ಟೈಮ್ ಮಾರುಕಟ್ಟೆ ದರ',
    realTimeCropNews: 'ರಿಯಲ್-ಟೈಮ್ ಬೆಳೆ ಸುದ್ದಿ',
    liveLocationNewsAdvisories: 'ನಿಮ್ಮ ಸ್ಥಳದ ಕೃಷಿ ಸುದ್ದಿ',
    localPeerProof: 'ಸ್ಥಳೀಯ ಸಹ-ರೈತರ ಪುರಾವೆ',
    similarFarms: 'ಸಮಾನ ಹೊಲಗಳು',
    creditLoanMatching: 'ಸಾಲ ಹೊಂದಾಣಿಕೆ',
    personalizedFinancing: 'ವೈಯಕ್ತಿಕ ಸಾಲ ಆಯ್ಕೆಗಳು.',
    maxAmount: 'ಗರಿಷ್ಠ ಮೊತ್ತ',
    interestRate: 'ಬಡ್ಡಿ ದರ',
    processing: 'ಪ್ರಕ್ರಿಯೆ',
    days: 'ದಿನಗಳು',
    uiToday: 'ಇಂದು',
    humShort: 'ಆರ್ದ್ರತೆ',
    rain: 'ಮಳೆ',
    priority: 'ಆದ್ಯತೆ',
    uiQuickTools: 'ತ್ವರಿತ ಪರಿಕರಗಳು',
    listen: 'ಆಲಿಸಿ',
    stop: 'ನಿಲ್ಲಿಸಿ',
    tapToListen: 'ಕೇಳಲು ಒತ್ತಿ',
  },
  bn: {
    appName: 'AgriN',
    appSubtitle: 'BRICS ডিজিটাল নেটওয়ার্ক',
    overview: 'সংক্ষিপ্ত বিবরণ',
    aiTools: 'AI সরঞ্জাম',
    farmIntelligence: 'কৃষি বুদ্ধিমত্তা',
    marketsAndCommunity: 'বাজার ও সম্প্রদায়',
    settings: 'সেটিংস',
    logout: 'লগ আউট',
    loggedInAs: 'লগ ইন:',
    dashboard: 'ড্যাশবোর্ড',
    smartAlerts: 'স্মার্ট সতর্কতা',
    cropDiagnostics: 'ফসল রোগনির্ণয়',
    agroBot: 'অ্যাগ্রোবট AI',
    satelliteMap: 'উপগ্রহ মানচিত্র',
    weather: 'আবহাওয়া',
    yieldPredictor: 'ফলন পূর্বাভাস',
    fieldScouting: 'মাঠ পরিদর্শন',
    marketPrices: 'বাজার দর',
    bricsExchange: 'জ্ঞান বিনিময়',
    goodMorning: 'সুপ্রভাত',
    goodAfternoon: 'শুভ দুপুর',
    goodEvening: 'শুভ সন্ধ্যা',
    farmer: 'কৃষক',
    soilHealth: 'মাটির স্বাস্থ্য',
    optimal: 'সর্বোত্তম',
    moisture: 'আর্দ্রতা',
    phLevel: 'pH মাত্রা',
    nitrogen: 'নাইট্রোজেন (N)',
    phosphorus: 'ফসফরাস (P)',
    currentConditions: 'বর্তমান অবস্থা',
    temperature: 'তাপমাত্রা',
    humidity: 'আর্দ্রতা',
    windSpeed: 'বাতাসের গতি',
    uvIndex: 'UV সূচক',
    farmOverview: 'খামার সংক্ষিপ্ত বিবরণ',
    activeFields: 'সক্রিয় জমি',
    cropHealthAvg: 'ফসল স্বাস্থ্য গড়',
    pendingAlerts: 'মুলতুবি সতর্কতা',
    nextHarvest: 'পরবর্তী ফসল কাটা',
    cropVigorNDVI: 'ফসল বৃদ্ধি (NDVI)',
    sentinelData: 'Sentinel-2 তথ্য',
    aiAdvisories: 'AI পরামর্শ',
    coverCropping: 'আচ্ছাদন ফসল সুপারিশ',
    irrigationAlert: 'সেচ সতর্কতা',
    welcomeBack: 'পুনরায় স্বাগতম',
    signInAccount: 'অ্যাকাউন্টে সাইন ইন করুন',
    createAccount: 'অ্যাকাউন্ট তৈরি করুন',
    joinNetwork: 'BRICS কৃষি নেটওয়ার্কে যোগ দিন',
    email: 'ইমেইল',
    password: 'পাসওয়ার্ড',
    confirmPassword: 'পাসওয়ার্ড নিশ্চিত করুন',
    fullName: 'পূর্ণ নাম',
    country: 'দেশ',
    signIn: 'সাইন ইন',
    register: 'নিবন্ধন',
    noAccount: 'অ্যাকাউন্ট নেই?',
    hasAccount: 'অ্যাকাউন্ট আছে?',
    signingIn: 'সাইন ইন হচ্ছে...',
    registering: 'নিবন্ধন হচ্ছে...',
    passwordStrength: 'পাসওয়ার্ড শক্তি',
    weak: 'দুর্বল',
    fair: 'মাঝারি',
    strong: 'শক্তিশালী',
    veryStrong: 'অত্যন্ত শক্তিশালী',
    sevenDayForecast: '৭-দিনের পূর্বাভাস',
    precipitationProb: 'বৃষ্টির সম্ভাবনা',
    aiFarmSchedule: 'AI কৃষি সময়সূচি',
    rainChance: 'বৃষ্টির সম্ভাবনা',
    wind: 'বাতাস',
    refresh: 'রিফ্রেশ',
    knowledgeExchange: 'জ্ঞান বিনিময়',
    shareKnowledge: 'জ্ঞান ভাগ করুন',
    publishToBrics: 'প্রকাশ করুন',
    searchTechniques: 'কৌশল খুঁজুন...',
    cancel: 'বাতিল',
    replies: 'উত্তর',
    autoTranslated: 'স্বয়ংক্রিয় অনুবাদ',
    marketPricesTitle: 'বাজার দর',
    refreshPrices: 'দর রিফ্রেশ',
    lastUpdated: 'সর্বশেষ আপডেট',
    sellNow: 'এখন বিক্রি করুন',
    hold: 'ধরে রাখুন',
    buyDip: 'কিনুন',
    aiSignal: 'AI সংকেত',
    yieldPredictorTitle: 'ফলন পূর্বাভাস',
    tonsPerHa: 'টন/হেক্টর',
    confidence: 'আত্মবিশ্বাস',
    estHarvest: 'আনুমানিক ফসল কাটা',
    growthProgress: 'বৃদ্ধি অগ্রগতি',
    adjustFactors: 'উপাদান সমন্বয়',
    yieldFactors: 'ফলন উপাদান',
    cropGrowthCalendar: 'ফসল বৃদ্ধি ক্যালেন্ডার',
    historicalYield: 'ঐতিহাসিক ফলন (টন/হে)',
    newScoutReport: 'নতুন প্রতিবেদন',
    totalReports: 'মোট প্রতিবেদন',
    highSeverity: 'উচ্চ তীব্রতা',
    fieldsScouted: 'পরিদর্শিত জমি',
    field: 'জমি',
    crop: 'ফসল',
    latitude: 'অক্ষাংশ',
    longitude: 'দ্রাঘিমাংশ',
    useGPS: 'GPS ব্যবহার করুন',
    severity: 'তীব্রতা',
    observations: 'পর্যবেক্ষণ',
    uploadPhoto: 'ফটো আপলোড',
    saveReport: 'প্রতিবেদন সংরক্ষণ',
    scoutHistory: 'পরিদর্শন ইতিহাস',
    low: 'কম',
    medium: 'মাঝারি',
    high: 'উচ্চ',
    smartAlertsTitle: 'স্মার্ট সতর্কতা',
    markAllRead: 'সব পঠিত চিহ্নিত করুন',
    disease: 'রোগ',
    weatherAlert: 'আবহাওয়া',
    market: 'বাজার',
    irrigation: 'সেচ',
    resolveAlert: 'সতর্কতা সমাধান',
    dismiss: 'বাতিল করুন',
    recommendedAction: 'সুপারিশকৃত পদক্ষেপ',
    agrobotTitle: 'অ্যাগ্রোবট AI সহকারী',
    agrobotSubtitle: 'BRICS ডেটাসেটে প্রশিক্ষিত',
    newChat: 'নতুন চ্যাট',
    askAgrobot: 'আপনার কৃষি সম্পর্কে অ্যাগ্রোবটকে জিজ্ঞাসা করুন...',
    agrobotDisclaimer: 'অ্যাগ্রোবট AI নির্দেশনা দেয়। গুরুত্বপূর্ণ সিদ্ধান্তের জন্য স্থানীয় বিশেষজ্ঞের পরামর্শ নিন.',
    satelliteMapTitle: 'উপগ্রহ মানচিত্র',
    satelliteSubtitle: 'রিয়েল-টাইম NDVI · Sentinel-2',
    avgFarmNdvi: 'গড় NDVI',
    totalFarmArea: 'মোট কৃষি এলাকা',
    activeStressZones: 'সক্রিয় চাপ অঞ্চল',
    offline: 'অফলাইন',
    retry: 'পুনরায় চেষ্টা',
    loading: 'লোড হচ্ছে...',
    noData: 'কোনো তথ্য নেই',
    aboveAvg: 'আঞ্চলিক গড়ের উপরে',
    whatShouldIDoToday: 'আজ আমার কী করা উচিত?',
    whatShouldIDoTodayDesc: 'আবহাওয়া ও ফসল চক্রের উপর ভিত্তি করে, এটি সবচেয়ে গুরুত্বপূর্ণ পদক্ষেপ.',
    sprayFungicideNow: 'এখন ছত্রাকনাশক স্প্রে করুন',
    viewDetails: 'বিস্তারিত দেখুন',
    verified: 'যাচাইকৃত',
    financialServices: 'আর্থিক সেবা',
    laborAndEquipment: 'শ্রমিক ও যন্ত্রপাতি',
    seedsAndInputs: 'বীজ ও উপকরণ',
    postHarvest: 'ফসল কাটার পর',
    transitionSupport: 'রূপান্তর সহায়তা',
    womenFarmers: 'মহিলা কৃষক',
    govtSchemes: 'সরকারি প্রকল্প',
    communityAndTrust: 'সম্প্রদায় ও বিশ্বাস',
    offlineMode: 'অফলাইন মোড',
    farmerServices: 'কৃষক সেবা',
    days: 'দিন',
    uiToday: 'আজ',
    humShort: 'আর্দ্রতা',
    rain: 'বৃষ্টি',
    priority: 'অগ্রাধিকার',
    uiQuickTools: 'দ্রুত সরঞ্জাম',
    listen: 'শুনুন',
    stop: 'থামুন',
    tapToListen: 'শুনতে চাপুন',
  },
  pa: {
    appName: 'AgriN',
    appSubtitle: 'BRICS ਡਿਜੀਟਲ ਨੈੱਟਵਰਕ',
    overview: 'ਸੰਖੇਪ',
    aiTools: 'AI ਸੰਦ',
    farmIntelligence: 'ਖੇਤੀ ਬੁੱਧੀ',
    marketsAndCommunity: 'ਬਾਜ਼ਾਰ ਅਤੇ ਭਾਈਚਾਰਾ',
    settings: 'ਸੈਟਿੰਗਾਂ',
    logout: 'ਲੌਗ ਆਉਟ',
    loggedInAs: 'ਲੌਗ ਇਨ:',
    dashboard: 'ਡੈਸ਼ਬੋਰਡ',
    smartAlerts: 'ਸਮਾਰਟ ਚੇਤਾਵਨੀਆਂ',
    cropDiagnostics: 'ਫ਼ਸਲ ਜਾਂਚ',
    agroBot: 'ਐਗਰੋਬੋਟ AI',
    satelliteMap: 'ਸੈਟੇਲਾਈਟ ਨਕਸ਼ਾ',
    weather: 'ਮੌਸਮ',
    yieldPredictor: 'ਝਾੜ ਅੰਦਾਜ਼ਾ',
    fieldScouting: 'ਖੇਤ ਸਰਵੇ',
    marketPrices: 'ਬਾਜ਼ਾਰ ਭਾਅ',
    bricsExchange: 'ਗਿਆਨ ਵਟਾਂਦਰਾ',
    goodMorning: 'ਸ਼ੁਭ ਸਵੇਰ',
    goodAfternoon: 'ਸ਼ੁਭ ਦੁਪਹਿਰ',
    goodEvening: 'ਸ਼ੁਭ ਸ਼ਾਮ',
    farmer: 'ਕਿਸਾਨ',
    soilHealth: 'ਮਿੱਟੀ ਦੀ ਸਿਹਤ',
    optimal: 'ਸਰਬੋਤਮ',
    moisture: 'ਨਮੀ',
    phLevel: 'pH ਪੱਧਰ',
    nitrogen: 'ਨਾਈਟ੍ਰੋਜਨ (N)',
    phosphorus: 'ਫਾਸਫੋਰਸ (P)',
    currentConditions: 'ਮੌਜੂਦਾ ਸਥਿਤੀ',
    temperature: 'ਤਾਪਮਾਨ',
    humidity: 'ਨਮੀ',
    windSpeed: 'ਹਵਾ ਦੀ ਰਫ਼ਤਾਰ',
    uvIndex: 'UV ਸੂਚਕ',
    farmOverview: 'ਖੇਤ ਸੰਖੇਪ',
    activeFields: 'ਸਰਗਰਮ ਖੇਤ',
    cropHealthAvg: 'ਫ਼ਸਲ ਸਿਹਤ ਔਸਤ',
    pendingAlerts: 'ਲੰਬਿਤ ਚੇਤਾਵਨੀਆਂ',
    nextHarvest: 'ਅਗਲੀ ਵਾਢੀ',
    cropVigorNDVI: 'ਫ਼ਸਲ ਵਾਧਾ (NDVI)',
    sentinelData: 'Sentinel-2 ਡਾਟਾ',
    aiAdvisories: 'AI ਸਲਾਹ',
    welcomeBack: 'ਮੁੜ ਜੀ ਆਇਆਂ ਨੂੰ',
    signInAccount: 'ਖਾਤੇ ਵਿੱਚ ਸਾਈਨ ਇਨ ਕਰੋ',
    createAccount: 'ਖਾਤਾ ਬਣਾਓ',
    email: 'ਈਮੇਲ',
    password: 'ਪਾਸਵਰਡ',
    fullName: 'ਪੂਰਾ ਨਾਂ',
    country: 'ਦੇਸ਼',
    signIn: 'ਸਾਈਨ ਇਨ',
    register: 'ਰਜਿਸਟਰ',
    sevenDayForecast: '੭-ਦਿਨ ਅੰਦਾਜ਼ਾ',
    refresh: 'ਰਿਫ਼ਰੈਸ਼',
    cancel: 'ਰੱਦ ਕਰੋ',
    sellNow: 'ਹੁਣੇ ਵੇਚੋ',
    hold: 'ਰੱਖੋ',
    buyDip: 'ਖ਼ਰੀਦੋ',
    whatShouldIDoToday: 'ਅੱਜ ਮੈਂ ਕੀ ਕਰਾਂ?',
    viewDetails: 'ਵੇਰਵੇ ਦੇਖੋ',
    verified: 'ਪ੍ਰਮਾਣਿਤ',
    financialServices: 'ਵਿੱਤੀ ਸੇਵਾਵਾਂ',
    seedsAndInputs: 'ਬੀਜ ਅਤੇ ਸਮੱਗਰੀ',
    postHarvest: 'ਵਾਢੀ ਤੋਂ ਬਾਅਦ',
    womenFarmers: 'ਔਰਤ ਕਿਸਾਨ',
    govtSchemes: 'ਸਰਕਾਰੀ ਸਕੀਮਾਂ',
    offlineMode: 'ਆਫ਼ਲਾਈਨ ਮੋਡ',
    farmerServices: 'ਕਿਸਾਨ ਸੇਵਾਵਾਂ',
    days: 'ਦਿਨ',
    uiToday: 'ਅੱਜ',
    rain: 'ਮੀਂਹ',
    low: 'ਘੱਟ',
    medium: 'ਮੱਧ',
    high: 'ਵੱਧ',
    disease: 'ਬਿਮਾਰੀ',
    market: 'ਬਾਜ਼ਾਰ',
    irrigation: 'ਸਿੰਚਾਈ',
    offline: 'ਆਫ਼ਲਾਈਨ',
    loading: 'ਲੋਡ ਹੋ ਰਿਹਾ...',
    noData: 'ਕੋਈ ਡਾਟਾ ਨਹੀਂ',
    listen: 'ਸੁਣੋ',
    stop: 'ਰੁਕੋ',
    tapToListen: 'ਸੁਣਨ ਲਈ ਦਬਾਓ',
  },
  gu: {
    appName: 'AgriN',
    appSubtitle: 'BRICS ડિજિટલ નેટવર્ક',
    overview: 'ઝાંખી',
    aiTools: 'AI સાધનો',
    farmIntelligence: 'ખેતી બુદ્ધિમત્તા',
    marketsAndCommunity: 'બજાર અને સમુદાય',
    settings: 'સેટિંગ્સ',
    logout: 'લૉગ આઉટ',
    loggedInAs: 'લૉગ ઇન:',
    dashboard: 'ડેશબોર્ડ',
    smartAlerts: 'સ્માર્ટ ચેતવણી',
    cropDiagnostics: 'પાક નિદાન',
    agroBot: 'એગ્રોબોટ AI',
    satelliteMap: 'ઉપગ્રહ નકશો',
    weather: 'હવામાન',
    yieldPredictor: 'ઉત્પાદન અંદાજ',
    fieldScouting: 'ખેત સર્વે',
    marketPrices: 'બજાર ભાવ',
    bricsExchange: 'જ્ઞાન વિનિમય',
    goodMorning: 'શુભ સવાર',
    goodAfternoon: 'શુભ બપોર',
    goodEvening: 'શુભ સાંજ',
    farmer: 'ખેડૂત',
    soilHealth: 'માટીનું આરોગ્ય',
    optimal: 'શ્રેષ્ઠ',
    moisture: 'ભેજ',
    phLevel: 'pH સ્તર',
    nitrogen: 'નાઈટ્રોજન (N)',
    phosphorus: 'ફોસ્ફરસ (P)',
    currentConditions: 'વર્તમાન સ્થિતિ',
    temperature: 'તાપમાન',
    humidity: 'ભેજ',
    windSpeed: 'પવનની ગતિ',
    uvIndex: 'UV અનુક્રમણિકા',
    farmOverview: 'ખેત ઝાંખી',
    activeFields: 'સક્રિય ખેતરો',
    cropHealthAvg: 'પાક આરોગ્ય સરેરાશ',
    pendingAlerts: 'બાકી ચેતવણી',
    nextHarvest: 'આગામી લણણી',
    cropVigorNDVI: 'પાક વૃદ્ધિ (NDVI)',
    sentinelData: 'Sentinel-2 ડેટા',
    aiAdvisories: 'AI સલાહ',
    welcomeBack: 'ફરી સ્વાગત',
    signInAccount: 'ખાતામાં સાઇન ઇન કરો',
    createAccount: 'ખાતું બનાવો',
    email: 'ઈમેલ',
    password: 'પાસવર્ડ',
    fullName: 'પૂરું નામ',
    country: 'દેશ',
    signIn: 'સાઇન ઇન',
    register: 'નોંધણી',
    sevenDayForecast: '૭-દિવસનો અંદાજ',
    refresh: 'રિફ્રેશ',
    cancel: 'રદ કરો',
    sellNow: 'હવે વેચો',
    hold: 'રાખો',
    buyDip: 'ખરીદો',
    whatShouldIDoToday: 'આજે મારે શું કરવું?',
    viewDetails: 'વિગતો જુઓ',
    verified: 'ચકાસાયેલ',
    financialServices: 'નાણાકીય સેવાઓ',
    seedsAndInputs: 'બીજ અને ખાતર',
    postHarvest: 'લણણી પછી',
    womenFarmers: 'મહિલા ખેડૂત',
    govtSchemes: 'સરકારી યોજનાઓ',
    offlineMode: 'ઑફલાઇન મોડ',
    farmerServices: 'ખેડૂત સેવાઓ',
    days: 'દિવસ',
    uiToday: 'આજે',
    rain: 'વરસાદ',
    low: 'ઓછું',
    medium: 'મધ્યમ',
    high: 'વધુ',
    disease: 'રોગ',
    market: 'બજાર',
    irrigation: 'સિંચાઈ',
    offline: 'ઑફલાઇન',
    loading: 'લોડ થઈ રહ્યું છે...',
    noData: 'કોઈ ડેટા નથી',
    listen: 'સાંભળો',
    stop: 'બંધ કરો',
    tapToListen: 'સાંભળવા દબાવો',
  },
  or: {
    appName: 'AgriN',
    appSubtitle: 'BRICS ଡିଜିଟାଲ ନେଟୱର୍କ',
    overview: 'ସାରାଂଶ',
    aiTools: 'AI ଉପକରଣ',
    farmIntelligence: 'କୃଷି ବୁଦ୍ଧିମତ୍ତା',
    marketsAndCommunity: 'ବଜାର ଓ ସମାଜ',
    settings: 'ସେଟିଂସ',
    logout: 'ଲଗ ଆଉଟ',
    loggedInAs: 'ଲଗ ଇନ:',
    dashboard: 'ଡ୍ୟାସବୋର୍ଡ',
    smartAlerts: 'ସ୍ମାର୍ଟ ସତର୍କତା',
    cropDiagnostics: 'ଫସଲ ନିଦାନ',
    agroBot: 'ଆଗ୍ରୋବଟ AI',
    satelliteMap: 'ଉପଗ୍ରହ ମାନଚିତ୍ର',
    weather: 'ପାଣିପାଗ',
    yieldPredictor: 'ଅମଳ ଆକଳନ',
    fieldScouting: 'କ୍ଷେତ୍ର ସର୍ବେକ୍ଷଣ',
    marketPrices: 'ବଜାର ଦର',
    goodMorning: 'ଶୁଭ ସକାଳ',
    goodAfternoon: 'ଶୁଭ ଅପରାହ୍ନ',
    goodEvening: 'ଶୁଭ ସନ୍ଧ୍ୟା',
    farmer: 'କୃଷକ',
    soilHealth: 'ମାଟିର ସ୍ବାସ୍ଥ୍ୟ',
    temperature: 'ତାପମାତ୍ରା',
    humidity: 'ଆର୍ଦ୍ରତା',
    whatShouldIDoToday: 'ଆଜି ମୁଁ କ\'ଣ କରିବି?',
    viewDetails: 'ବିବରଣୀ ଦେଖନ୍ତୁ',
    verified: 'ଯାଞ୍ଚ ହୋଇଛି',
    financialServices: 'ଆର୍ଥିକ ସେବା',
    seedsAndInputs: 'ବିହନ ଓ ଉପକରଣ',
    postHarvest: 'ଅମଳ ପରେ',
    womenFarmers: 'ମହିଳା କୃଷକ',
    govtSchemes: 'ସରକାରୀ ଯୋଜନା',
    offlineMode: 'ଅଫଲାଇନ ମୋଡ',
    farmerServices: 'କୃଷକ ସେବା',
    days: 'ଦିନ',
    uiToday: 'ଆଜି',
    rain: 'ବର୍ଷା',
    low: 'କମ',
    medium: 'ମଧ୍ୟମ',
    high: 'ଅଧିକ',
    disease: 'ରୋଗ',
    market: 'ବଜାର',
    irrigation: 'ସେଚ',
    offline: 'ଅଫଲାଇନ',
    loading: 'ଲୋଡ ହେଉଛି...',
    noData: 'କୌଣସି ଡାଟା ନାହିଁ',
    listen: 'ଶୁଣନ୍ତୁ',
    stop: 'ବନ୍ଦ କରନ୍ତୁ',
    tapToListen: 'ଶୁଣିବାକୁ ଦବାନ୍ତୁ',
  },
  as: {
    appName: 'AgriN',
    appSubtitle: 'BRICS ডিজিটেল নেটৱৰ্ক',
    overview: 'সাৰাংশ',
    aiTools: 'AI সঁজুলি',
    farmIntelligence: 'কৃষি বুদ্ধিমত্তা',
    marketsAndCommunity: 'বজাৰ আৰু সম্প্ৰদায়',
    settings: 'ছেটিংছ',
    logout: 'লগ আউট',
    loggedInAs: 'লগ ইন:',
    dashboard: 'ডেচব\'ৰ্ড',
    smartAlerts: 'স্মাৰ্ট সতৰ্কতা',
    cropDiagnostics: 'শস্য নিৰ্ণয়',
    agroBot: 'এগ্ৰ\'বট AI',
    satelliteMap: 'উপগ্ৰহ মানচিত্ৰ',
    weather: 'বতৰ',
    yieldPredictor: 'উৎপাদন পূৰ্বানুমান',
    fieldScouting: 'পথাৰ সমীক্ষা',
    marketPrices: 'বজাৰ দৰ',
    goodMorning: 'শুভ পুৱা',
    goodAfternoon: 'শুভ দুপৰীয়া',
    goodEvening: 'শুভ সন্ধিয়া',
    farmer: 'কৃষক',
    soilHealth: 'মাটিৰ স্বাস্থ্য',
    temperature: 'তাপমাত্ৰা',
    humidity: 'আৰ্দ্ৰতা',
    whatShouldIDoToday: 'আজি মই কি কৰিম?',
    viewDetails: 'বিৱৰণ চাওক',
    verified: 'প্ৰমাণিত',
    financialServices: 'বিত্তীয় সেৱা',
    womenFarmers: 'মহিলা কৃষক',
    govtSchemes: 'চৰকাৰী আঁচনি',
    offlineMode: 'অফলাইন মোড',
    farmerServices: 'কৃষক সেৱা',
    days: 'দিন',
    uiToday: 'আজি',
    rain: 'বৰষুণ',
    offline: 'অফলাইন',
    loading: 'ল\'ড হৈ আছে...',
    noData: 'কোনো ডেটা নাই',
    listen: 'শুনক',
    stop: 'ৰওক',
    tapToListen: 'শুনিবলৈ টিপক',
  },
  bh: {
    appName: 'AgriN',
    appSubtitle: 'BRICS डिजिटल नेटवर्क',
    overview: 'झांकी',
    aiTools: 'AI औजार',
    farmIntelligence: 'खेती बुद्धि',
    marketsAndCommunity: 'बाजार आ समुदाय',
    settings: 'सेटिंग',
    logout: 'लॉगआउट',
    loggedInAs: 'लॉगइन:',
    dashboard: 'डैशबोर्ड',
    smartAlerts: 'स्मार्ट चेतावनी',
    cropDiagnostics: 'फसल जांच',
    agroBot: 'एग्रोबोट AI',
    satelliteMap: 'सैटेलाइट नक्शा',
    weather: 'मौसम',
    yieldPredictor: 'पैदावार अंदाज',
    fieldScouting: 'खेत सर्वे',
    marketPrices: 'बाजार भाव',
    goodMorning: 'सुप्रभात',
    goodAfternoon: 'नमस्कार',
    goodEvening: 'शुभ संध्या',
    farmer: 'किसान',
    soilHealth: 'माटी के स्वास्थ्य',
    temperature: 'तापमान',
    humidity: 'नमी',
    whatShouldIDoToday: 'आज हमरा का करे के बा?',
    viewDetails: 'विवरण देखीं',
    verified: 'प्रमाणित',
    financialServices: 'वित्तीय सेवा',
    seedsAndInputs: 'बीया आ सामान',
    postHarvest: 'कटनी के बाद',
    womenFarmers: 'महिला किसान',
    govtSchemes: 'सरकारी योजना',
    offlineMode: 'ऑफलाइन मोड',
    farmerServices: 'किसान सेवा',
    days: 'दिन',
    uiToday: 'आज',
    rain: 'बरखा',
    low: 'कम',
    medium: 'मध्यम',
    high: 'ज्यादा',
    disease: 'रोग',
    market: 'बाजार',
    irrigation: 'सिंचाई',
    offline: 'ऑफलाइन',
    loading: 'लोड हो रहा बा...',
    noData: 'कवनो डेटा नइखे',
    listen: 'सुनीं',
    stop: 'रुकीं',
    tapToListen: 'सुने खातिर दबाईं',
  },
  raj: {
    appName: 'AgriN',
    appSubtitle: 'BRICS डिजिटल नेटवर्क',
    overview: 'झांकी',
    aiTools: 'AI साधन',
    farmIntelligence: 'खेती बुद्धि',
    marketsAndCommunity: 'बाजार अर समाज',
    settings: 'सेटिंग',
    logout: 'लॉगआउट',
    loggedInAs: 'लॉगइन:',
    dashboard: 'डैशबोर्ड',
    smartAlerts: 'स्मार्ट चेतावनी',
    cropDiagnostics: 'फसल जांच',
    agroBot: 'एग्रोबोट AI',
    satelliteMap: 'सैटेलाइट नक्शो',
    weather: 'मौसम',
    yieldPredictor: 'पैदावार अंदाजो',
    fieldScouting: 'खेत सर्वे',
    marketPrices: 'बाजार भाव',
    goodMorning: 'राम राम सा',
    goodAfternoon: 'खम्मा घणी',
    goodEvening: 'राम राम सा',
    farmer: 'किसान',
    soilHealth: 'माटी रो स्वास्थ्य',
    temperature: 'तापमान',
    humidity: 'नमी',
    whatShouldIDoToday: 'आज म्हानै कांई करणो है?',
    viewDetails: 'ब्यौरो देखो',
    verified: 'प्रमाणित',
    financialServices: 'आर्थिक सेवा',
    seedsAndInputs: 'बीज अर खाद',
    postHarvest: 'कटाई रे बाद',
    womenFarmers: 'बाई किसान',
    govtSchemes: 'सरकारी योजना',
    offlineMode: 'ऑफलाइन मोड',
    farmerServices: 'किसान सेवा',
    days: 'दिन',
    uiToday: 'आज',
    rain: 'बरसात',
    low: 'कम',
    medium: 'मध्यम',
    high: 'घणो',
    disease: 'रोग',
    market: 'बाजार',
    irrigation: 'सिंचाई',
    offline: 'ऑफलाइन',
    loading: 'लोड हो रह्यो है...',
    noData: 'कोई डेटा कोनी',
    listen: 'सुणो',
    stop: 'रुको',
    tapToListen: 'सुणण नैं दबाओ',
  },
  bgc: {
    appName: 'AgriN',
    appSubtitle: 'BRICS डिजिटल नेटवर्क',
    overview: 'झांकी',
    aiTools: 'AI औजार',
    farmIntelligence: 'खेती बुद्धि',
    marketsAndCommunity: 'बाजार अर भाईचारा',
    settings: 'सेटिंग',
    logout: 'लॉगआउट',
    loggedInAs: 'लॉगइन:',
    dashboard: 'डैशबोर्ड',
    smartAlerts: 'स्मार्ट चेतावनी',
    cropDiagnostics: 'फसल जांच',
    agroBot: 'एग्रोबोट AI',
    satelliteMap: 'सैटेलाइट नक्शा',
    weather: 'मौसम',
    yieldPredictor: 'पैदावार अंदाजा',
    fieldScouting: 'खेत सर्वे',
    marketPrices: 'मंडी भाव',
    goodMorning: 'राम राम ताऊ',
    goodAfternoon: 'राम राम भाई',
    goodEvening: 'राम राम',
    farmer: 'किसान',
    soilHealth: 'माट्टी की सेहत',
    temperature: 'तापमान',
    humidity: 'नमी',
    whatShouldIDoToday: 'आज मन्नै के करणा है?',
    viewDetails: 'ब्यौरा देखो',
    verified: 'प्रमाणित',
    financialServices: 'पैसे की सेवा',
    seedsAndInputs: 'बीज अर खाद',
    postHarvest: 'कटाई कै बाद',
    womenFarmers: 'लुगाई किसान',
    govtSchemes: 'सरकारी योजना',
    offlineMode: 'ऑफलाइन मोड',
    farmerServices: 'किसान सेवा',
    days: 'दिन',
    uiToday: 'आज',
    rain: 'बरसात',
    low: 'कम',
    medium: 'बीचला',
    high: 'घणा',
    disease: 'बीमारी',
    market: 'मंडी',
    irrigation: 'सिंचाई',
    offline: 'ऑफलाइन',
    loading: 'लोड हो रहा है...',
    noData: 'कोई डेटा ना',
    listen: 'सुणो',
    stop: 'रुको',
    tapToListen: 'सुणन खातर दबाओ',
  },
};

module.exports = translations;
